### ISSUE TITLE
Six calendar wrong WeekendChristmas and WeekendBoxingDay

### ISSUE THREAD

**Issue by vvacc** [rsheftel/pandas_market_calendars#100]
Hi All,

it seems that for six calendar WeekendChristmas and WeekendBoxingDay are wrongly applied.

See for example 28-12-2020, this is a non business day according current implementation (due to Boxing Day happening on Saturday and shifted to the next Monday), while looking to six calendar (https://www.six-group.com/exchanges/download/participants/regulation/trading_guides/trading_calendar_2020.pdf) it actually is a trading day.

Many thanks

**Comment by rsheftel** [comment]
@oliverfu89 , you created the initial SIX calendar in PR #36 . Before I change it, do you have any insight into this issue?

**Comment by rsheftel** [comment]
This is being worked on here if you would like to contribute or check;

https://github.com/rsheftel/pandas_market_calendars/tree/six-fix

**Comment by rsheftel** [comment]
This is fixed in #101
