### ISSUE TITLE
Question: NYSE calendar by no NASDAQ calendar

### ISSUE THREAD

**Issue by hmanfarmer** [rsheftel/pandas_market_calendars#104]
I assume having an NYSE calendar and no NASDAQ calendar is intentional, considering NASDAQ is listed as an alias for NYSE in the source. But, I am confused. Historically, has the NASDAQ open days exactly matched the NYSE open days?

I am trying to ascertain what risks there are when using the NYSE calendar for NASDAQ stocks. Maybe this is a question that could be addressed in the documentation?

**Comment by rsheftel** [comment]
Yes, historically and most likely going forward all equity markets in the US share the same calendar. So the NYSE and the NASDAQ have the same open/close times, holidays and early closes. There is no need for a separate NASDAQ calendar.
