### ISSUE TITLE
CFE Valid Days Missing  April 3, 2015

### ISSUE THREAD

**Issue by dougransom** [rsheftel/pandas_market_calendars#116]
Good Fridays are valid trade days when Christmas or New Years Day fall on a Friday.  

[https://www.cboe.com/trading-resources/cfe-expiration-holiday-calendars
](https://www.cboe.com/trading-resources/cfe-expiration-holiday-calendars
)
`import pandas_market_calendars as mcal
cfe =  mcal.get_calendar('CFE')
valid_days=cfe.valid_days(start_date='2015-04-01', end_date='2015-04-6')
print(f"Valid days {valid_days}")`

`Valid days DatetimeIndex(['2015-04-01 00:00:00+00:00', '2015-04-02 00:00:00+00:00',
               '2015-04-06 00:00:00+00:00'],
              dtype='datetime64[ns, UTC]', freq='C')`

**Comment by rsheftel** [comment]
That is a crazy rule. If you want to submit a PR that is great, otherwise I will look to add this when I can.

**Comment by rsheftel** [comment]
@dougransom , the latest version 1.6 of this now imports all of the calendars in the trading_calendars project, see #120 for more details. Can you take a look at the "XCBF" calendar and see if the problem exists there or is correct. This is the calendar for the CBOE Exchange from the trading_calendars project. Thanks.

@jmccorriston
@richafrank
@gerrymanoim

**Comment by rsheftel** [comment]
This is now fixed in trading_calendars [#171](https://github.com/quantopian/trading_calendars/pull/171) so it is available in the pandas_market_calendars under calendar XCBF. Thanks for the Issue.

**Comment by rsheftel** [comment]
This is now fixed in commit f5879b9b51b8942a890f3c56ee67903d4f78fdc1 and v1.6.1 in PyPi
