### ISSUE TITLE
How to deal with Forex

### ISSUE THREAD

**Issue by markusmaresch** [rsheftel/pandas_market_calendars#118]
This is more a question, than an issue.
I was looking, but did not find the market calendar for Forex: https://www.forex.com/en/support/trading-hours
Now, I believe there is no need to have it, because it is basically CME, without any holiday - no rules needed. But is it ?
Thanks for your kind explanation of how to deal with this in the best way in the context of pandas_market_calendars
Best Regards
Markus

**Comment by rsheftel** [comment]
I am not very aware of Forex.com the service. Is this just a place to trade FX? If so then there is no real "market" or "exchange" for FX in that it is a 24/7 market that is completely over-the-counter. That said it does follow a set of customs on when trading is. Are you looking for Forex.com or the FX market?

**Comment by markusmaresch** [comment]
Yes, my bad - I was not precise enough. Basically I am looking for when the over-the-counter forex market is open for trading. It appears basically "always minus Fri: 17-24 CET, minus all Saturday, minus Sun: 0-17h CET" - (=CME !!) that was the reason for my investigation. And I could not find a good enough answer yet

**Comment by rsheftel** [comment]
If the FX calendar maps to the CME, then feel free to use that. If you would like to make a new "FX" calendar and submit a PR please go ahead.

**Comment by markusmaresch** [comment]
Ok thanks. Please mark this closeed
