### ISSUE TITLE
Calendar CME not observing Labor Day

### ISSUE THREAD

**Issue by markusmaresch** [rsheftel/pandas_market_calendars#119]
It appears, that CME does not observe Labour Day.

`import pandas_market_calendars`
`cme = pandas_market_calendars.get_calendar('CME')`
`cme.schedule(start_date='2020-09-04', end_date='2020-09-09')`

Labor Day: 2020/09/07 should be NOT shown
[https://www.cmegroup.com/tools-information/holiday-calendar.html]

**Comment by rsheftel** [comment]
The generic CME calendar is the super-set of open days. I would recommend using the specific product calendar:

https://pandas-market-calendars.readthedocs.io/en/latest/calendars.html#futures-calendars
