### ISSUE TITLE
EUREX calendar

### ISSUE THREAD

**Issue by fin-eng** [rsheftel/pandas_market_calendars#12]
The EUREX calendar has 1st of May dates included in "valid_days", although correctly marked as holidays.

**Comment by rsheftel** [comment]
I cannot find the error you mention. I added a new Eurex test in the test/ directory and the following code correctly detects the May 1st holiday (falling on 2nd May 2016) as not in valid_days. I also checked for 2017 and the code is correct. Can you post some code that does not correctly exclude the May 1st holiday from the valid_days. Thanks.

`def test_2016_holidays():
    # good friday: 2016-03-25
    # May 1st: 2016-05-02
    # christmas (observed): 2016-12-26
    # new years (observed): 2016-01-02
    eurex = EUREXExchangeCalendar()
    good_dates = eurex.valid_days('2016-01-01', '2016-12-31')
    for date in ["2016-03-25", "2016-05-02", "2016-12-26", "2016-01-02"]:
        assert pd.Timestamp(date, tz='UTC') not in good_dates
`

**Comment by fin-eng** [comment]
Hi there,

Thanks for coming back on that.

The rule applied seems incorrect to me, i. e. when 1st May is on a weekend Eurex will be open following Monday (2016). At least for all major markets. 

When 1st is on Monday it is completely closed (this was the case in 2017).

Please refer to the trading calendar and switch between 2016 and 2017

http://www.eurexchange.com/exchange-en/trading/trading-calendar/153700!tradingcalendar?state=H4sIAAAAAAAAAGWOwQrCMBBEf0X2nEOV1kNugnpSKCqCx5BsNbA2uLtBSum_GwuenNMy84adEYJT3HN6gl02Vd2sV3X1lZmDS_qzO-dRBew4lTuy6AFVkcH2mcjAI6q0yK27Y6nOjdh7ygHPUVF-WOppaEMHtnMkaOCVkQewAAYYJZNeI75_sCTWksm2LFo48QXyjo4plBdw221OMH0Aw8r3bMgAAAA&calMode=YEAR&day=20170501 <http://www.eurexchange.com/exchange-en/trading/trading-calendar/153700!tradingcalendar?state=H4sIAAAAAAAAAGWOwQrCMBBEf0X2nEOV1kNugnpSKCqCx5BsNbA2uLtBSum_GwuenNMy84adEYJT3HN6gl02Vd2sV3X1lZmDS_qzO-dRBew4lTuy6AFVkcH2mcjAI6q0yK27Y6nOjdh7ygHPUVF-WOppaEMHtnMkaOCVkQewAAYYJZNeI75_sCTWksm2LFo48QXyjo4plBdw221OMH0Aw8r3bMgAAAA&calMode=YEAR&day=20170501>

In general I think you’ll also have an issue with Christmas because in Germany in general you’ll have holidays on weekends, which won’t be rolled over to the next business day.

**Comment by rsheftel** [comment]
@kewlfft since you made the initial contribution for the Eurex calendar do you have any thoughts on this? It does look correct that the package needs a fix but I would like to get your input before proceeding.

**Comment by kewlfft** [comment]
I designed the Eurex calendar pretty quickly to address most of the cases but i am not surpised it needs to be fine tuned. I can look more into it over the weekend but dont hesitate to correct directly if you have time.

**Comment by kewlfft** [comment]
@fin-eng for 1st of May I see your point, it will be closed for some markets (British, Russian, Irish) and for commo derivatives but not fully closed on monday if the 1st falls on a weekend. If we follow the rule 'fully closed' then we shouldn't shift the day. agreed.

**Comment by rsheftel** [comment]
@kewlfft if you could make the change this weekend that would be great. Note that I made a test file for the Eurex calendar so you can use that if you want to add some unit tests

**Comment by kewlfft** [comment]
@rsheftel I made the change and tested on 2016 and 2017, @fin-eng if you can also check if it is good now for May

**Comment by kewlfft** [comment]
@fin-eng if you give me an example of issue for Christmas I can look into it as well

**Comment by rsheftel** [comment]
@fin-eng I updated the Eurex unit tests (2d43560a2e2402bd7c344c636ed6ea9d344327e8) if you could use that to identify if the work @kewlfft is good or not. If there is something incorrect can you please update the tests to what should be correct, then we have something to test against. Thanks.

**Comment by fin-eng** [comment]
Thank you guys. I have look at it on the weekend with my dataset as well.

Just as a broad rule, in Germany holidays on weekends are not rolled to the next business day also for Christmas. So this should hold same as for May.

**Comment by kewlfft** [comment]
@fin-eng @rsheftel I can propose a fix for Christmas if you have an actual example that we can check on the Eurex site it would help. Eurex covers many markets other than Germany and could adopt different rules.

**Comment by kewlfft** [comment]
@fin-eng @rsheftel I think the May 1st fix is quite safe to merge, then waiting for some concrete examples of Christmas to fix this one too if needed

**Comment by rsheftel** [comment]
@kewlfft I merged in your PR #15 last week as commit 73949896688bb7dbe207d5bdee979bc6842e699c. We are all up to date now. @fin-eng if you come up with more examples of dates to correct that would be great. I am going to close this now, please open a new comment with new dates. thanks.
