### ISSUE TITLE
Changes in regular opening hours

### ISSUE THREAD

**Issue by jbtheming** [rsheftel/pandas_market_calendars#123]
On the EUREX exchange for fixed income derivatives such as Bund/Bobl/Buxl/Shatz futures the regular market open and close times have changed over the years. 
For example prior to 2005 the hours were 08:00 - 19:00 CET, from 2005 to 2018 they were 08:00 - 22:00 CET, and from 2019 onwards they were changed to 01:10 to 22:00 CET.  
I can't see an obvious way to implement this calendar as things stand....am I missing something or is this something that needs to be considered as an enhancement?

**Comment by gerrymanoim** [comment]
In trading_calendars, we can support multiple ope/closes like this https://github.com/quantopian/trading_calendars/blob/master/trading_calendars/exchange_calendar_xhkg.py#L278

**Comment by rsheftel** [comment]
@gerrymanoim you beat me to it.

@jbtheming , as @gerrymanoim mentioned this functionality exists in trading_calendars. And as of v1.6 (the latest on PyPi) of pandas_market_calendars , all calendars in trading_calendars are brought in and can be accessed from pandas_market_calendars in addition to form trading_calendars itself.

As such, it would be great if you could implement the Eurex calendar in trading_calendars if you would like.

Thanks.

**Comment by jbtheming** [comment]
@gerrymanoim Thank you.

@rsheftel Yes, I can certainly implement it. As well as the German futures I mentioned above, I can implement a calendar for the French OAT futures that trade on Eurex too, as they trade different hours. Are there any conventions I should follow when creating calendars for different instruments on the same exchange? 

I've also been using the CME/CBOT Bond future calendar that only exists in pandas_market_calendars, and have identified a few additional rules for special closes, and a couple of ad-hoc closes that need to be added to it. Should I make those changes in pandas_market_calendars, or instead just create a new calendar in trading_calendars?

Lastly, the Australian treasury future contracts on ASX have fun rules around opening /closing times such as

> "5.10pm to 7.00am and 8.30am to 4.30pm (for period from second Sunday in March to first Sunday in November) 5.10pm to 7.30am and 8.30am to 4.30pm (for period from first Sunday in November to second Sunday in March)"

[(as described on pages 4 & 6 here)](https://www.asx.com.au/documents/products/3-and-10-year-treasury-bond-futures-factsheet.pdf)....would the best way of handling this just be a hard-coded set of  open_times and close_times?

**Comment by gerrymanoim** [comment]
We have CME/CBOT in https://github.com/quantopian/trading_calendars/blob/master/trading_calendars/exchange_calendar_cmes.py (Let me know if I'm mistaken - I haven't done much futures trading).

**Comment by gerrymanoim** [comment]
As for the weird open times, you could do something like what we do here: https://github.com/quantopian/trading_calendars/blob/84b92e3e693ce52a5ba19bb025c114c629c1ebaa/trading_calendars/exchange_calendar_xsgo.py#L214 (write a generator that yields the right data on demand)

**Comment by jbtheming** [comment]
Yeah I saw that @gerrymanoim, it's a kind of generalization around the rules for the various contracts that trade:

> For now, we will treat the CME as having a single calendar, and just go with the most conservative hours 

pandas_market_calendars has specific implementations [https://github.com/rsheftel/pandas_market_calendars/blob/master/pandas_market_calendars/exchange_calendar_cme.py](https://github.com/rsheftel/pandas_market_calendars/blob/master/pandas_market_calendars/exchange_calendar_cme.py) for each of equity, agricultural and fixed income contracts. I guess I'm just not sure to which repo you would like me to submit any changes on this one? 

The generator approach for ASX seems like a better way to go too, so I'll follow that pattern.

**Comment by gerrymanoim** [comment]
I'm happy to accept the pr in `trading_calendars`. Also open to refactoring the CME calendar in trading calendars, that's generally been community driven and we're going to do a major version bump anyway. 

@rsheftel - what do you think?

**Comment by rsheftel** [comment]
Here are my thoughts on the right path with the end goal of making trading_calendars be the best source.

- trading_calendars is doing a major refactor that will allow for the concept of an intra-day "lunch break". That is needed for any of the future markets that pause trading intra-day for processing and the like. 

- Once that release is done, it would make sense to copy over the Eurex implementation from pandas_market_calendars to trading_calendars with the improvements you think it should have.

- Then copy over the structure from pandas_market_calendars of having a calendar implementation by product type. In futures (unlike equities) every product is so different that they are effectively different exchanges.

So what does that mean for right now?
- If you can implement Eurex in trading_calendars the do it
- Once the lunch-break is in trading_calendars we can work to move over the CME/CBOT product specific calenders.

**Comment by gerrymanoim** [comment]
I'll check up on the status of that lunch break PR.

**Comment by jmccorriston** [comment]
@jbtheming On Quantopian, we used to use the generalized calendar that you referenced to drive the simulation engine. Basically, each trading day on the generalized calendar was a day that an algorithm should check all its calculations and data. However, as you're discussing in this thread, there are some contracts that have extra holidays or other oddities about their trading schedule that aren't captured in that general implementation. We never really solved for that exception other than having 0 volume in minute bars whenever a particular contract wasn't trading (that was just an artifact of the data). In our context, it was important for an algorithm to be able to consider trading contracts with different trading schedules. In fact, I believe we even created a "US Futures" calendar which was used the **intersection** of the holidays on each of the component exchange calendars (CME, CBOT, etc.). 

If you don't mind sharing, I'm curious how are you planning to use the different contract trading schedules. I know that the Quantopian implementation wasn't perfect so I'm wondering how you are thinking of using futures trading calendars downstream. I find it extremely helpful to think of use cases while designing/maintaining interfaces.

Sorry if this question is a little off topic from the rest of the thread!

**Comment by jbtheming** [comment]
Hi @jmccorriston I don't use Quantopian but I do need to be able to perform simple date and time calculations such as "what is the date x trading days after y for contract A" and "time x trading hours before market close on date y for contract B".  

I also have to contend with "noisy" quote data that contain non-executable submissions to the order book made during the periods such as pre-open when the exchanges are closed for trading. 
Having accurate trading calendars - and the ability to generate DatetimeIndex from these - allows me to filter out these quotes from my time series.

**Comment by rsheftel** [comment]
@jmccorriston just my two cents, and this may apply to others. In running a pairs or stat arb like strategy, what I care about is when ALL the markets are open, as I can only deal with days that all symbols are trading. So I would like to know the actual trading days for each market, and then do an intersection of those.
