### ISSUE TITLE
incorrect operation on pandas 1.1.3

### ISSUE THREAD

**Issue by drusakov778** [rsheftel/pandas_market_calendars#124]
I have not yet have a full test snippet for it, but basically it appears that on 'NASDAQ' calendars the latest pandas-market-calendars 1.6.0 works incorrectly with latest pandas 1.1.3, operation on pandas 1.0.5 is fine.

tested on both python 3.8.5 and python 3.7.9

exceprt from my internal printout, pandas=1.1.3, pandas-market-calendars=1.6.0:
```
...
2020-10-08 18:36:05 INFO TSLA: collecting data: 2020-10-01 - 2020-10-07
2020-10-08 18:36:05 DEBUG TSLA: pandas-market-calendars reports a holiday on 2020-10-01. date skipped
2020-10-08 18:36:05 DEBUG TSLA: pandas-market-calendars reports a holiday on 2020-10-02. date skipped
2020-10-08 18:36:05 DEBUG TSLA: pandas-market-calendars reports a holiday on 2020-10-05. date skipped
2020-10-08 18:36:05 DEBUG TSLA: pandas-market-calendars reports a holiday on 2020-10-06. date skipped
2020-10-08 18:36:05 DEBUG TSLA: pandas-market-calendars reports a holiday on 2020-10-07. date skipped
2020-10-08 18:36:05 INFO TSLA: 0 dates collected in 0.00 seconds, total of 0 bars written
...
```

the same code using pandas 1.0.5 works just fine.

I will aim to update this ticker on Monday with the small code excerpt demonstrating the problem

**Comment by rsheftel** [comment]
I am not getting that result. Using a new environment, mcal v1.6 and pandas 1.1.3 I get:

```
Python 3.8.5 (default, Sep  4 2020, 07:30:14) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pandas_market_calendars as mcal
>>> nasdaq = mcal.get_calendar('NASDAQ')
>>> nasdaq
<pandas_market_calendars.exchange_calendar_nyse.NYSEExchangeCalendar object at 0x7f25137c66d0>
>>> import pandas as pd
>>> pd.__version__
'1.1.3'
>>> schedule = nasdaq.schedule(start_date='2020-10-07', end_date='2020-10-10')
>>> mcal.date_range(schedule, '1D')
DatetimeIndex(['2020-10-07 20:00:00+00:00', '2020-10-08 20:00:00+00:00',
               '2020-10-09 20:00:00+00:00'],
              dtype='datetime64[ns, UTC]', freq='D')
```

**Comment by drusakov778** [comment]
Will review and reconfirm from my side on Monday

**Comment by drusakov778** [comment]
here is exact code snippet demonstrating a problem

```
import sys
import datetime as dt
import pandas as pd
import pandas_market_calendars as mcal

print('python:', sys.version)
print('pandas:', pd.__version__)
print('pandas_market_calendars:', mcal.__version__)

start_date = dt.date(2020, 10, 1)
end_date = dt.date(2020, 10, 3)
exchange = 'NASDAQ'

exch_mcal = mcal.get_calendar(exchange)
schedule = exch_mcal.schedule(start_date=start_date, end_date=end_date)

print(exchange, 'schedule:', schedule.index)

for date in pd.date_range(start_date, end_date):
    date = date.date()      # pd.date_range() returns datetime
    print('checking:', date)
    if date not in schedule.index:
        print('pandas-market-calendars reports a holiday on', date, '. date skipped')
```

returns on pandas 1.0.5
```
python: 3.7.9 (default, Sep  6 2020, 16:32:30) 
[Clang 10.0.1 (clang-1001.0.46.4)]
pandas: 1.0.5
pandas_market_calendars: 1.6.0
NASDAQ schedule: DatetimeIndex(['2020-10-01', '2020-10-02'], dtype='datetime64[ns]', freq='C')
checking: 2020-10-01
checking: 2020-10-02
checking: 2020-10-03
pandas-market-calendars reports a holiday on 2020-10-03 . date skipped
```

and on pandas 1.1.3 (and also 1.1.0)
```
python: 3.7.9 (default, Sep  6 2020, 16:32:30) 
[Clang 10.0.1 (clang-1001.0.46.4)]
pandas: 1.1.3
pandas_market_calendars: 1.6.0
NASDAQ schedule: DatetimeIndex(['2020-10-01', '2020-10-02'], dtype='datetime64[ns]', freq=None)
checking: 2020-10-01
pandas-market-calendars reports a holiday on 2020-10-01 . date skipped
checking: 2020-10-02
pandas-market-calendars reports a holiday on 2020-10-02 . date skipped
checking: 2020-10-03
pandas-market-calendars reports a holiday on 2020-10-03 . date skipped
```

this is obviously related to the conversion I am making in line 20 'date = date.date()', without which code works fine on both pandas versions, but it will be nice to support checking the dates when they are given also as date and not only as 'datetime'. At least this was working pre pandas 1.1.0

**Comment by rsheftel** [comment]
It definitely appears this is a change in behavior in the pandas library and not pandas_market_calendars. I can confirm that converting a pandas Timestamp to a datetime and then using the "in" comparison on the DateTimeIndex no longer works after pandas 1.1.0. From the whats new it looks like there are lots of changes to the DateTimeIndex in v1.1.0 (https://pandas.pydata.org/docs/whatsnew/v1.1.0.html)

I also know that the assert_frame_equal() changed behavior in 1.1.0 with regards to comparison on DateTimeIndex, so this may be the same issue.

Regardless I think you could solve your problem by either:

1. Not converting the date to datetime and leaving it as a pandas TimeStamp or
2. using the mcal "date_range" function to get a date range directly from the schedule so you know you only have valid dates.

**Comment by drusakov778** [comment]
thank you for looking into it. pandas does change a lot and it is a pain. 

From my side the easiest is probably just to fix pandas version to 1.0.5 until it's treatment for DateTimeIndexes will settle down.

Just for the sake of better understanding and pinning down the issue I've experimented with using mcal.date_range() and 'valid_days' for determining the list of non-holiday days instead of direct 'in' comparison.

I can not get mcal.date_range() to work neither for pandas 1.0.5 or 1.1.3 with timestamp only, I am most likely not using it correctly. But a 'valid_days()' function on exchange calendar seems to work fine and is happily supporting 'datetime.date' in pandas 1.0.5 and only supporting 'datetime.datetime' in pandas 1.1.3 (similar to 'in' check on index itself)

tested with the code similar to posted originally, relevant sections can be commented/uncommented at the end
```
import sys
import datetime as dt
import pandas as pd
import pandas_market_calendars as mcal

print('python:', sys.version)
print('pandas:', pd.__version__)
print('pandas_market_calendars:', mcal.__version__)

start_date = dt.date(2020, 10, 1)
end_date = dt.date(2020, 10, 3)
exchange = 'NASDAQ'

exch_mcal = mcal.get_calendar(exchange)
valid_days = exch_mcal.valid_days(start_date=start_date, end_date=end_date)
schedule = exch_mcal.schedule(start_date=start_date, end_date=end_date)
sch_date_range = mcal.date_range(schedule, '1D')

print(exchange, 'valid_days:', valid_days)
print(exchange, 'schedule.index:', schedule.index)
print(exchange, "mcal.date_range(schedule, '1D'):", sch_date_range)

for date in pd.date_range(start_date, end_date):
    # date = date.date()      # pd.date_range() returns datetime
    print('checking:', date)
    if date not in valid_days:
    # if date not in schedule.index:
    # if date not in sch_date_range:    # does not work neither in pandas 1.0.5 or 1.1.3
        print('pandas-market-calendars reports a holiday on', date, '. date skipped')
```

**Comment by rsheftel** [comment]
You are doing it correctly. the mcal.date_range() is a wrapper around pd.date_range() and will use the schedule you provide to return a range of dates and times that are in the valid schedule. So you could just replace the "pd.date_range(...)" in your for loop with "sch_date_range" and you should get by definition everything in the range is valid. I hope that helps.

**Comment by drusakov778** [comment]
Thank you
