### ISSUE TITLE
suggestion: support crypto-markets in pandas_market_calendars

### ISSUE THREAD

**Issue by drusakov778** [rsheftel/pandas_market_calendars#126]
goal: expand pandas_market_calendars to support crypto exchanges, e.g. Binance

Rationale: for trading projects working across the different asset classes it will be beneficial to process exchange calendar information in a unified way

**Comment by rsheftel** [comment]
I am open to adding any crypto exchange you submit to this. The framework should be flexible enough to not just cover stock exchanges, but futures, FX, OTC or crypto.

Go ahead an submit a PR of any crypto exchange with tests and I will take a look.
