### ISSUE TITLE
convert_freq returning incorrect dates

### ISSUE THREAD

**Issue by dynoweb** [rsheftel/pandas_market_calendars#129]
While trying to get the last trading day of each month, I noticed that it was reporting some incorrect trading dates.

To reproduce:
nyse = mcal.get_calendar('NYSE')
schedule = nyse.schedule(start_date = datetime(2014, 6, 1), end_date = datetime(2015, 1, 1))
eom = pd.DataFrame(mcal.convert_freq(schedule.index, frequency='1m'))
eom

  | 0
-- | --
2014-06-30
2014-07-31
2014-08-31
2014-09-30
2014-10-31
2014-11-30
2014-12-31

Sunday, August 31, 2014
Notice that 2014-8-31 should be 2014-8-29

**Comment by rsheftel** [comment]
You are correct. The code for convert_freq is just a convenience wrapper around the pandas ".asfreq()" method and in the process of converting the frequency it looses knowledge of the holiday calendar and weekends when you use the frequency "1M". To preserve the holidays use the "1CBM" (for Custom Business Month end) per the docs: 

https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html#timeseries-offset-aliases

```
>>> eom = pd.DataFrame(mcal.convert_freq(schedule.index, frequency='1CBM'))
>>> eom
           0
0 2014-06-30
1 2014-07-31
2 2014-08-29
3 2014-09-30
4 2014-10-31
5 2014-11-28
6 2014-12-31

```

**Comment by dynoweb** [comment]
Verified
