### ISSUE TITLE
UK Holidays in 2022 are a bit special

### ISSUE THREAD

**Issue by ashb** [rsheftel/pandas_market_calendars#130]
https://www.gov.uk/bank-holidays and https://www.gov.uk/government/news/extra-bank-holiday-to-mark-the-queens-platinum-jubilee-in-2022

Date | DoW | Name
-- | -- | --
3 January | Monday | New Year’s Day (substitute day)
15 April | Friday | Good Friday
18 April | Monday | Easter Monday
2 May | Monday | Early May bank holiday
2 June | Thursday | Spring bank holiday
3 June | Friday | Platinum Jubilee bank holiday
29 August | Monday | Summer bank holiday
26 December | Monday | Boxing Day
27 December | Tuesday | Christmas Day (substitute day)

Specifically the Spring bank holiday is on a Thursday (normally it is a Monday!) and then the one off Platinum Jubilee bank holiday.

I'm not sure how to encode this (I've only just started looking at this library) else I would attempt a PR myself.

**Comment by rsheftel** [comment]
Thank you very much for this. Fixed and committed 4b2ba3ef81a6a01a287c2e74fd0fd59091bd494d
