### ISSUE TITLE
CME's default open time and close time is 17:00-16:00 CT

### ISSUE THREAD

**Issue by yukoba** [rsheftel/pandas_market_calendars#131]
Basically, the CME's default open time and close time is 17:00-16:00 CT.
https://www.cmegroup.com/trading-hours.html

Why
https://github.com/rsheftel/pandas_market_calendars/blob/1.6/pandas_market_calendars/exchange_calendar_cme.py#L56
and
https://github.com/rsheftel/pandas_market_calendars/blob/1.6/pandas_market_calendars/exchange_calendar_cme.py#L171
are 17:01-17:00 CT?

**Comment by rsheftel** [comment]
The generic CME calendar encompasses all the trading hours of all contracts on the CME. This is generally not useful and instead you should use a calendar specific to the product:

https://pandas-market-calendars.readthedocs.io/en/latest/calendars.html#futures-calendars

**Comment by yukoba** [comment]
Currently,

- CMEExchangeCalendar - 17:01 - 17:00 CT
- CMEEquityExchangeCalendar - 17:00 - 16:00 CT (18:00 - 17:00 ET)
- CMEAgricultureExchangeCalendar - 17:01 - 17:00 CT
- CMEBondExchangeCalendar - 17:00 - 16:00 CT

and I think they all should be 17:00 - 16:00 CT.

But to be precise, it's more complicated than 17:00 - 16:00 CT. All the products have different trading hours in CME. This page is convenient. https://futuresonline.com/education/products/trading-hours/?by=Exchange Please select CME, CBOT, COMEX, and NYMEX for the CME group.

**Comment by rsheftel** [comment]
@yukoba you are correct that in some futures complex, like agricultural, there is a unique open and close time for each product. I would encourage you to create a child class that inherits from MarketCalendar for any specific contract or product group and submit a PR. I will review and add.

**Comment by yukoba** [comment]
I'm sorry, but I decided not to use these classes. I just wanted to report. Forgive me for closing this issue.
