### ISSUE TITLE
CME is open on Good Friday 2021 for Interest Rate products

### ISSUE THREAD

**Issue by tvr101** [rsheftel/pandas_market_calendars#132]
Since non-farm payrolls falls on good friday in this year, 2021-04-02, the CME is open for an abbreviated session for fx and interest rate products (CME_Rate calendar). Settlement is 10am CST, but Globex remains open until 10:15 CST.

https://www.cmegroup.com/tools-information/holiday-calendar/files/2021-good-friday-holiday-schedule.xls
https://www.cmegroup.com/tools-information/holiday-calendar/files/good-friday-holiday-settlement-times-2021.pdf

[2021-good-friday-holiday-schedule.xlsx](https://github.com/rsheftel/pandas_market_calendars/files/6247020/2021-good-friday-holiday-schedule.xlsx)
[good-friday-holiday-settlement-times-2021.pdf](https://github.com/rsheftel/pandas_market_calendars/files/6247026/good-friday-holiday-settlement-times-2021.pdf)

**Comment by rsheftel** [comment]
Thank you for this. Fixed in commit 4e2649472f8f9c2c06ad2b3de2c5aa3d5a5d182c
