### ISSUE TITLE
NYSE calendar

### ISSUE THREAD

**Issue by glossner** [rsheftel/pandas_market_calendars#135]
If you check [ this link](https://www.mathworks.com/help/finance/nyseclosures.html), Matlab has a function that returns NYSE trading days.

I briefly looked through your code and changing AbstractHolidayCalendar.start_date = '1900-01-01' to 1885 is easy. However, allowing Saturday closes thru 5/24/1952 seems problematic. You have weekmask in market_calendar.py but I guess changing this will cause unintended side effects.

Any thoughts? 

Thanks.

**Comment by rsheftel** [comment]
This is the most comprehensive list of holidays for NYSE back to 1885 that I have seen. You could update the code and the tests to modify for these early dates. Its probably best to use the formulaic definitions of holidays if possible, otherwise use the ad_hoc to just list exact dates, which since they are in the past using fixed numbers is not a risk as they will not change.

**Comment by glossner** [comment]
I will give it a shot. 

I guess the main issue is how to include Saturdays without affecting every other calendar.  

Any thoughts?

Thanks.

**Comment by rsheftel** [comment]
You could override the weekmask method for the NYSE calendar to include Saturday, and then add a custom holiday of every Saturday after a given date when the NYSE stopped being open on Saturdays.

That should get you what is needed without effecting other calendars

**Comment by glossner** [comment]
I have this working in my fork without breaking your nyse tests. I'm finding a number of rules that need updating (start dates, etc.). I'm fixing them as I find them. It may take a couple of weeks as I'm traveling next week.

Thanks for the hint. It was very easy to implement.

**Comment by glossner** [comment]
I've figured out how to specify additional times for early closings. Is there any way to write a rule that says the market was open from 11am to 1pm on a particular day?

If interested, you can see what I'm doing at my fork. I'm up to 1920. I'll send you a pull request when I get through all the years. 

Thanks.

**Comment by glossner** [comment]
Sorry, that should have said is there any way to write a rule that says the market was CLOSED from 11am to 1pm.

**Comment by glossner** [comment]
There is also one other point for discussion. The way Saturdays are added back in using a week mask means that after 1952 every Saturday is interpreted as a Holiday. My guess is the vast majority of users will not want this behavior. I'm thinking it is probably better to have two separate calendars - one pre 1952 and one post 1952. Those who want the earlier years can join the two calendars. Thoughts?

**Comment by glossner** [comment]
Ignore the question about multiple calendars. I figured out how to override valid_days and schedule to make it transparent.

I still need to figure out if it is possible to have 1 or more breaks during the day.  Thanks.

**Comment by rsheftel** [comment]
> Sorry, that should have said is there any way to write a rule that says the market was CLOSED from 11am to 1pm.

I think that the only way to solve this would be to define that as the break. There is code for break start & break end. Look at some of the other calendars for examples.

**Comment by rsheftel** [comment]
> Ignore the question about multiple calendars. I figured out how to override valid_days and schedule to make it transparent.
> 
> I still need to figure out if it is possible to have 1 or more breaks during the day. Thanks.

I don't think there is a way right now to have multiple breaks on a single day. You could add that functionality, but not something out of the box.

**Comment by rsheftel** [comment]
In my comment above I mentioned about an excellent and complete historical NYSE calendar, but I never sent it. 
[Stocks NYSE-Closings.pdf](https://github.com/rsheftel/pandas_market_calendars/files/6827110/Stocks.NYSE-Closings.pdf)
[Stocks NYSE-Closings.xlsx](https://github.com/rsheftel/pandas_market_calendars/files/6827111/Stocks.NYSE-Closings.xlsx)

They are attached here if you want to cross-check your implementation.

**Comment by glossner** [comment]
I'm up to the year 2000 and seem to have everything working. 

I would like your design input. 

The file holidays_us.py is now huge and very specific to NYSE. The holidays are not the same as CME, JPX and probably others. I figured this out by fixing rules for other calendars that started failing tests.

My question is do you prefer:
1) a separate holidays_us_nyse.py file?
or
2) A single holidays_us.py file with a number of vestigial rules left in it such that it doesn't break other calendars?

You can look through my fork and decide. It is probably still a couple of weeks before I can send you a pull request.

Thanks.

**Comment by rsheftel** [comment]
For the NYSE specific holidays make a "holidays_nyse.py" file and put them in there. holidays_us should be universal and generic, like Xmas

**Comment by glossner** [comment]
I've now finished the updates. Let me know if there is anything you would like changed before I send a PR.

Changed files:
market_calendar.py: Added late_opens() analogous to early_closes()
holidays_nyse.py: General holidays that don't 100% follow US holidays. Special holidays since 1885.
exchange_calendar_nyse.py: 1885-2022 with all Saturdays, holidays, and special opens/closes supported.
test_nyse_calendar_early_years.py: A test for every year since 1885 including open/close time matches.

All test pass (doesn't break other calendars) except test_nyse_calendar->test_all_full_day_holidays_since_1928 because Saturdays are not included in this test.

Thanks!

**Comment by rsheftel** [comment]
did you add the late_opens() to the base class or just the NYSE? Would be nice if it was part of the base class

Can you update the failing test to make it pass?

**Comment by glossner** [comment]
Yes.

I put the default behavior with  in class MarketCalendar using self.open_time and then overrode it in exchange_calendar_nyse.py since for nyse it depends on the year for when the market opens.

**Comment by rsheftel** [comment]
OK sounds good. If you could just fix the failing test and submit the PR that would be great.

**Comment by glossner** [comment]
I can programmatically output to a new csv file all the days years since 1928 but they are already covered in the tests I wrote. Every year since 1885 is tested for every holiday, late open, and early close. It will be redundant but I will do it if you wish.

The reason it fails is because there are Saturdays that are holidays that were not holidays using a weekmask=Mon-Fri.

Please just confirm your preference. 

Thanks.

**Comment by rsheftel** [comment]
What is the start date for the weekend close? Maybe we move that test to just start on that date?

**Comment by glossner** [comment]
Start date for Saturday trading is probably 1871. I have data back to 1885 (where I set the calendar to begin). End date is technically Sept 27, 1952 but the last Saturday traded was  May 24, 1952.

I updated the csv to include Saturdays starting from 1928. Everything passes under python 3.8. Everything is pushed to my github fork if you want to look at it.

Anything else? 

Thanks.

**Comment by rsheftel** [comment]
Thanks. It would be easiest/best do submit the PR and then we can look at the diffs and go from there.

**Comment by glossner** [comment]
I deleted all the caches and did one last check of all the tests in the directory. I have 1 fail left: 
test_XNYS_calendar.py->test_all_full_day_holidays_since_1928()  (the mirrored calendar).

The rules for XNYS are generating holidays on Saturdays (even after 1952). Most of them are New Years Day.

I'm not sure how that is. I went and looked at the mirror site and they use a M-F weekmask.  I tested the weekmask for  xnys_cal  in the pytest and it is indeed M-F.

I only overrode the weekmask in class NYSEExchangeCalendar(MarketCalendar). Also they use their own holiday rules at the mirror site.

I can't see how anything I've done could affect XNYS. 

I will try to figure that out over the weekend. Any thoughts?

Thanks.

**Comment by rsheftel** [comment]
Don't worry about that. The pandas_market_calendars offers the option to wrap the trading_calendars package and access those, in this case via the XNYS exchange code.

The underlying calendars are maintained in this repo (https://github.com/gerrymanoim/exchange_calendars)

I would just delete that failing test. If/when that package updates from your work we can put it back in.

**Comment by glossner** [comment]
I figured out what is going on. It has to do with the definition of Holidays. The old CSV file includes Saturdays as Holidays. Jan 1, 2011 is an example.

This is a US Holiday but it isn't an exchange holiday because the exchange is naturally closed on Saturdays. I modified all the rules to not generate any Saturday Holidays after 1952. They are wholly contained in holidays_nyse.py and don't affect any other calendar. The project I'm working on needs the definition of an exchange holiday to be any day that should have been a trading day but is not because the exchange was closed. 

For XNYS and exchange_calendar_nyse.py this means they can't share the same CSV test file. 

I can put back the old CSV file for XNYS and update the nyse test with a new CSV or I can remove that one test from XNYS.

Thoughts? Thanks.

**Comment by rsheftel** [comment]
I think it is fine to remove that test from XNYS. The capability to access trading_calendars package calendars from pandas_market_calendars is a convenience functionality. The test for correctness of those calendars should be in that package. I added some tests in this package mostly because I already had them laying around. 

So bottom line, as long as you fully test your new calendar code then I am fine with dropping that test from the XNYS test suite.

**Comment by glossner** [comment]
Ok. Sounds good. I'll do a last check over the weekend and send you a PR. Thanks.
