### ISSUE TITLE
NP_NAT error when attempting to import pandas_market_calender

### ISSUE THREAD

**Issue by thistleknot** [rsheftel/pandas_market_calendars#137]
https://stackoverflow.com/questions/68249890/np-nat-error-when-attempting-to-import-pandas-market-calender
\0

I'm trying things out on windows vs linux where I have this working in 3.8 and 3.9.5, but not on windows using anaconda

import sys
sys.path.append("../")
from datetime import time
import pandas as pd
import pandas_market_calendars as mcal
error

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\User\Anaconda3\envs\py39\lib\site-packages\pandas_market_calendars\__init__.py", line 19, in <module>
    from .calendar_registry import get_calendar, get_calendar_names
  File "C:\Users\User\Anaconda3\envs\py39\lib\site-packages\pandas_market_calendars\calendar_registry.py", line 21, in <module>
    from .exchange_calendars_mirror import *
  File "C:\Users\User\Anaconda3\envs\py39\lib\site-packages\pandas_market_calendars\exchange_calendars_mirror.py", line 9, in <module>
    import exchange_calendars
  File "C:\Users\User\Anaconda3\envs\py39\lib\site-packages\exchange_calendars\__init__.py", line 16, in <module>
    from .calendar_utils import (
  File "C:\Users\User\Anaconda3\envs\py39\lib\site-packages\exchange_calendars\calendar_utils.py", line 3, in <module>
    from .always_open import AlwaysOpenCalendar
  File "C:\Users\User\Anaconda3\envs\py39\lib\site-packages\exchange_calendars\always_open.py", line 5, in <module>
    from .exchange_calendar import ExchangeCalendar
  File "C:\Users\User\Anaconda3\envs\py39\lib\site-packages\exchange_calendars\exchange_calendar.py", line 27, in <module>
    from .calendar_helpers import (
  File "C:\Users\User\Anaconda3\envs\py39\lib\site-packages\exchange_calendars\calendar_helpers.py", line 6, in <module>
    NP_NAT = np.array([pd.NaT], dtype=np.int64)[0]
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NaTType

**Comment by thistleknot** [comment]
When I run this inside a jupyterlab off oracle linux 8 w python 3.9.5, no issue

**Comment by thistleknot** [comment]
oddly enough it doesn't work in 3.9.6 in the same environment.  Something must have changed between 3.9.5 and 3.9.6

**Comment by Stryder-Git** [comment]
I have had the same issue using python 3.8.6 on Windows 10, and I just figured out that downgrading pandas from 1.3.0 to 1.2.5 solves the problem and lets all pytests pass.

From my console:
```
import pandas as pd
import numpy as np
pd.__version__
>> '1.3.0'
np.__version__
>> '1.21.0'

NP_NAT = np.array([pd.NaT], dtype=np.int64)   # <<-- The broken line in exchange_calendars.calendar_helpers.py
>> Traceback (most recent call last):
  File "<input>", line 1, in <module>
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NaTType'  

NP_NAT = np.array([pd.NaT])
>> ####  No problem
```` 
after downgrade:
```
import pandas as pd
import numpy as np
pd.__version__
>> '1.2.5'
np.__version__
>> '1.21.0'

NP_NAT = np.array([pd.NaT], dtype=np.int64)
>> #### No problem
```

**Comment by abachurin** [comment]
Same issue, first appeared about 1 hour ago. I am working in the same environment last month.

**Comment by abachurin** [comment]
> Does this fix work for you, @thistleknot, @abachurin?

Yes thank you! I actually first encountered there bug when tried to run my app in Docker, and i had pandas>= ... in requirements.txt . Fixed to pandas==1.2.5

**Comment by thistleknot** [comment]
fixed with @Stryder-Git suggestion of pandas==1.2.5

**Comment by impredicative** [comment]
> fixed with @Stryder-Git suggestion of pandas==1.2.5

That's a workaround more than it is a fix. The real fix to this package to support pandas==1.3.0 is pending.

**Comment by Stryder-Git** [comment]
#[This](https://github.com/gerrymanoim/exchange_calendars/pull/41) may be the actual fix

**Comment by rsheftel** [comment]
The error is with the underlying exchange_calendars package (https://github.com/gerrymanoim/exchange_calendars). It appears that error has been fixed in that package. If you update the exchange_calendars package everything will work fine. Nothing to do in this package.

Fix: https://github.com/gerrymanoim/exchange_calendars/pull/41
