### ISSUE TITLE
How to get the last trading day of the week? 

### ISSUE THREAD

**Issue by shuaiwang88** [rsheftel/pandas_market_calendars#139]
Thank you for providing this wonderful calendar. I am scratching my head to get the last trading date of the week for NYSE. I don't know how to take advance of this library. Any help will be appreciated. Thanks!

**Comment by rsheftel** [comment]
One way to do this would be to get the date_range using this https://pandas-market-calendars.readthedocs.io/en/latest/usage.html#date-range and then take that date range and use the pandas functionality to get the last day of the week/month/year etc as described here: https://stackoverflow.com/questions/31996872/getting-the-date-of-the-last-day-of-this-week-month-quarter-year

**Comment by rsheftel** [comment]
Please re-open if you have any more questions
