### ISSUE TITLE
failure on import

### ISSUE THREAD

**Issue by andydoc** [rsheftel/pandas_market_calendars#143]
`import pandas_market_calendars as mcal`

gives

> ---------------------------------------------------------------------------
> TypeError                                 Traceback (most recent call last)
> /tmp/ipykernel_1329/1039345194.py in <module>
> ----> 1 import pandas_market_calendars as mcal
>       2 #nyse = mcal.get_calendar('NYSE')
>       3 #nyse.valid_days(start_date='2000-01-01', end_date='2017-01-10')
> 
> /opt/miniconda3/envs/conda_env/lib/python3.9/site-packages/pandas_market_calendars/__init__.py in <module>
>      17 import pkg_resources
>      18 
> ---> 19 from .calendar_registry import get_calendar, get_calendar_names
>      20 from .calendar_utils import convert_freq, date_range, merge_schedules
>      21 # TODO: is the below needed? Can I replace all the imports on the calendars with ".market_calendar"
> 
> /opt/miniconda3/envs/conda_env/lib/python3.9/site-packages/pandas_market_calendars/calendar_registry.py in <module>
>      19 from .exchange_calendar_bse import BSEExchangeCalendar
>      20 from .exchange_calendar_tase import TASEExchangeCalendar
> ---> 21 from .trading_calendars_mirror import *
>      22 
>      23 
> 
> /opt/miniconda3/envs/conda_env/lib/python3.9/site-packages/pandas_market_calendars/trading_calendars_mirror.py in <module>
>       9 from datetime import time
>      10 from .market_calendar import MarketCalendar
> ---> 11 import trading_calendars
>      12 
>      13 
> 
> /opt/miniconda3/envs/conda_env/lib/python3.9/site-packages/trading_calendars/__init__.py in <module>
>      14 # limitations under the License.
>      15 
> ---> 16 from .trading_calendar import TradingCalendar
>      17 from .calendar_utils import (
>      18     clear_calendars,
> 
> /opt/miniconda3/envs/conda_env/lib/python3.9/site-packages/trading_calendars/trading_calendar.py in <module>
>      31 import toolz
>      32 
> ---> 33 from .calendar_helpers import (
>      34     NP_NAT,
>      35     compute_all_minutes,
> 
> /opt/miniconda3/envs/conda_env/lib/python3.9/site-packages/trading_calendars/calendar_helpers.py in <module>
>       4 NANOSECONDS_PER_MINUTE = int(6e10)
>       5 
> ----> 6 NP_NAT = np.array([pd.NaT], dtype=np.int64)[0]
>       7 
>       8 
> 
> TypeError: int() argument must be a string, a bytes-like object or a number, not 'NaTType'

using google slate:

> Python 3.9.6 | packaged by conda-forge | (default, Jul  6 2021, 08:53:59) 
> Type 'copyright', 'credits' or 'license' for more information
> IPython 7.25.0 -- An enhanced Interactive Python. Type '?' for help.

**Comment by rsheftel** [comment]
Can you confirm what version of mcal and what version of exchange_calendars you have installed? The problem is usually with the exchange_calendars package that mcal uses, make sure to update that to the latest.

**Comment by burnzy** [comment]
I had this same issue. Had upgraded to `pandas-market-caledars==3.0` and had `exchange-calendars==3.1.0`

Upgrading to ` exchange-calendars==3.3` resolved the issue

**Comment by rsheftel** [comment]
The new version 3.1 on PyPi sets a minimum version of exchange_calendars to 3.3, which will avoid the underlying problem. This is now resolved.
