### ISSUE TITLE
New maintainers

### ISSUE THREAD

**Issue by rsheftel** [rsheftel/pandas_market_calendars#145]
@Stryder-Git and @glossner, thank you for all your contributions to this package. I would like to add you as maintainers to this repo if that is something you are willing to do to help this package grow. Let me know.

**Comment by glossner** [comment]
@rsheftel I'm actively using the package so sure. Happy to help.

**Comment by Stryder-Git** [comment]
@rsheftel, That sounds good to me!

**Comment by rsheftel** [comment]
Thank you both
