### ISSUE TITLE
1999 Christmas day missing in holidays

### ISSUE THREAD

**Issue by bacharsam** [rsheftel/pandas_market_calendars#146]
Hi - I am using pandas market calendars package in my algorithm in COLAB. I realized that 24 December 1999 was a christmas day and was a holiday in NYSE and In the 3.7 python version this date does not appear in the holidays . 
You can see below the holidays :
(numpy.datetime64('1999-02-15'),
 numpy.datetime64('1999-04-02'),
 numpy.datetime64('1999-05-31'),
 numpy.datetime64('1999-07-05'),
 numpy.datetime64('1999-09-06'),
 **numpy.datetime64('1999-11-25'),**
 numpy.datetime64('2000-01-17'),
 numpy.datetime64('2000-02-21'),
 numpy.datetime64('2000-04-21'),
 numpy.datetime64('2000-05-29')) 

See below the installation notification : 
Collecting pandas_market_calendars
  Downloading pandas_market_calendars-3.1-py3-none-any.whl (84 kB)
     |████████████████████████████████| 84 kB 2.4 MB/s 
Requirement already satisfied: pandas>=0.18 in /usr/local/lib/python3.7/dist-packages (from pandas_market_calendars) (1.1.5)
Requirement already satisfied: pytz in /usr/local/lib/python3.7/dist-packages (from pandas_market_calendars) (2018.9)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.7/dist-packages (from pandas_market_calendars) (2.8.2)
Collecting exchange-calendars>=3.3
  Downloading exchange_calendars-3.3.tar.gz (129 kB)
     |████████████████████████████████| 129 kB 21.8 MB/s 
Requirement already satisfied: numpy in /usr/local/lib/python3.7/dist-packages (from exchange-calendars>=3.3->pandas_market_calendars) (1.19.5)
Collecting pyluach
  Downloading pyluach-1.3.0-py3-none-any.whl (17 kB)
Requirement already satisfied: toolz in /usr/local/lib/python3.7/dist-packages (from exchange-calendars>=3.3->pandas_market_calendars) (0.11.1)
Requirement already satisfied: korean_lunar_calendar in /usr/local/lib/python3.7/dist-packages (from exchange-calendars>=3.3->pandas_market_calendars) (0.2.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil->pandas_market_calendars) (1.15.0)

**Comment by glossner** [comment]
Christmas (12/25) in 1999 was a Saturday. The market would naturally have been closed so it isn't a market holiday.

I did notice that 12/24 is coded as an early close. This is incorrect. The market was closed all day as it was a Friday.

I will fix that shortly. 

Thanks for catching it.

**Comment by rsheftel** [comment]
Resolved in #147
