### ISSUE TITLE
NYSE Exchange Calendar

### ISSUE THREAD

**Issue by Stryder-Git** [rsheftel/pandas_market_calendars#151]
@glossner I have been working on an update for the MarketCalendar, which made me encounter a couple of things that I wanted your thoughts on.

* In holidays_nyse.py, the date 1990-12-24 was in both lists, ChristmasEve1pmEarlyCloseAdhoc and ChristmasEve2pmEarlyCloseAdhoc. In the tests you seem to be checking whether the close was at 2pm, so I removed the date from the 1pm list. This is correct, right?

* In a couple of places in NYSEExchangeCalendar, you (or shall I say we) rounded the times before 1901-12-14 because of a 4min timezone shift. Thinking about it, this may actually not be a good idea since technically that would be the incorrect time. Correct me if I'm wrong, but we would artifically be adding 4 minutes, and the following isn't what a user might expect:
```
sched = nyse.schedule("1901-12-12", "1901-12-16")
sched
>>>
                         market_open              market_close
1901-12-12 1901-12-12 15:00:00+00:00 1901-12-12 20:00:00+00:00
1901-12-13 1901-12-13 15:00:00+00:00 1901-12-13 20:00:00+00:00
1901-12-14 1901-12-14 15:00:00+00:00 1901-12-14 17:00:00+00:00
1901-12-16 1901-12-16 15:00:00+00:00 1901-12-16 20:00:00+00:00

sched.market_open.dt.tz_convert(nyse.tz)
>>>
1901-12-12   1901-12-12 10:04:00-04:56  # a user would have to know that these need to be rounded 
1901-12-13   1901-12-13 10:04:00-04:56  # and are actually 4 minutes off
1901-12-14   1901-12-14 10:00:00-05:00 
1901-12-16   1901-12-16 10:00:00-05:00
Name: market_open, dtype: datetime64[ns, America/New_York]

s
>>>
1901-12-12   1901-12-12 10:00:00-04:56
1901-12-13   1901-12-13 10:00:00-04:56
1901-12-14   1901-12-14 10:00:00-05:00
1901-12-16   1901-12-16 10:00:00-05:00
dtype: datetime64[ns, America/New_York]

s == sched.market_open
>>>
1901-12-12    False
1901-12-13    False
1901-12-14     True
1901-12-16     True
dtype: bool
```

If you want to, you can check out #150 PR and/or my fork, where I have implemented the calculations without rounding and have all tests pass with only minor tweaks.

Any thoughts or suggestions regarding this or the update are greatly appreciated.

**Comment by glossner** [comment]
I checked the source document and 2pm is the correct early close for 1990. So yes your change is correct. Thanks!

Rounding was put in to remove a bug in either tz_localize() or tz_convert(). If you remove round() you will find that prior to 1901-12-14 an incorrect result is returned with the times shifted by 4 minutes. I didn't look into why these early dates are shifted. If the tests pass without round() then it should be fine to remove it.

I will look in more detail but a quick scan of your diffs shows they greatly simplify exchange_calendar_nyse.py. Thanks!

**Comment by Stryder-Git** [comment]
After doing some research on this, it seems to be the change from the Local Mean Time system to whatever came after. I don't really understand the specifics yet but that is what timezone conversions are using (not just in pandas, actually). So, I think it's best to keep it as it is. I also posted a [question](https://stackoverflow.com/questions/69318097/why-is-there-a-4-minute-timezone-shift-between-ny-utc-on-1901-12-14) on stackoverflow, which might shine some light on this at some point.

The tests still pass, testing the same thing, which I will definitely double check before declaring the PR as ready.

And while I have your attention, I read through some of the comments in #135,  where you were wondering how to handle a special break and whether it is possible to have multiple breaks in a day.  This kind of functionality also passed my mind, but I wasn't sure if it was useful enough. 
Would you (or people you know of) still be interested in functionality for special breaks similar to special_closes/special_closes_adhoc and/or the ability to add multiple breaks in a day (that would also be respected by methods like is_open_now/open_at_time)?

**Comment by glossner** [comment]
@Stryder-Git I personally don't need breaks in the day for what I'm doing but I did put in a NOT IMPLEMENTED comment for every nyse break. If you add the capability I would be willing to code the rules for nyse.

**Comment by rsheftel** [comment]
@Stryder-Git are these changes part of your #150 PR, or did you make another branch to submit a different PR?

**Comment by Stryder-Git** [comment]
@rsheftel,These changes are already part of #150! Unless you disagree, I didn't consider this pressing enough to create a separate PR for it.

@glossner, Regarding special/multiple breaks, that may be a bit tricky to implement and only rarely used so I think I will keep that for a future date.

Thanks!
