### ISSUE TITLE
Schedule vs Unscheduled closures

### ISSUE THREAD

**Issue by ypraveen** [rsheftel/pandas_market_calendars#152]
@Stryder-Git Thanks for all your recent work on this! greatly appreciated.
@rsheftel Thanks for putting this together

We were using the NYSE calendar to figure out the short-trading days as the days when the closing time is not the same the regular default closing time. This worked well until the calendars are updated in one of the recent commits that added 2005 early closure due to system problems (SystemProb356pmEarlyClose2005)
https://github.com/rsheftel/pandas_market_calendars/blob/master/pandas_market_calendars/exchange_calendar_nyse.py#L235

Our code started detecting that day as a short trading day whereas it was really a "scheduled" full day.
This raised an interesting point: Currently these calendars are tracking all open/closures but don't track what was "scheduled" and what wasn't (aka disruption).

Wondering if we can add a flag to each "rule" to indicate whether it is scheduled or unscheduled?
Another option is to explicitly add a "declaration_timestamp" to each rule to track when a closure/closure-rule was declared. For the disruptions, declaration_timestamp could be same as the starting timestamp of a disruption window. For "US mourning" days, the declaration_timestamp will typically be 2-3 days ahead of those holidays when they were declared.

Comments?

Thanks!

**Comment by glossner** [comment]
I'm closing this as the data would be almost impossible to determine. If someone sends a pull request, I would review it. Thanks.
