### ISSUE TITLE
Thanksgiving days not working for NYSE

### ISSUE THREAD

**Issue by nirvana1122** [rsheftel/pandas_market_calendars#163]
import pandas_market_cal as mcal
from pandas.tseries.offsets import CustomBusinessDay
import date time as dt
BDay = CustumBusinessDay(calendar=mcal.get_calendar('NYSE'))

dt.date(2003,11,28) - BDay

return 2003-11-27(Thanks giving)

Can you please help? I created a wrapper where I manually try to append adhoc_holidays , and it's not working either

def calendar_wrapper(cal):

    if cal != 'NYSE':
        bDay = mcal.get_calendar(cal)
    else:
        bDay = mcal.get_calendar(cal)
        bDay.adhoc_holidays.append(pd.Timestamp('2000-11-23'))
        bDay.adhoc_holidays.append(pd.Timestamp('2001-11-22'))
        bDay.adhoc_holidays.append(pd.Timestamp('2002-11-28'))
        bDay.adhoc_holidays.append(pd.Timestamp('2003-11-27'))
        bDay.adhoc_holidays.append(pd.Timestamp('2004-11-25'))
        bDay.adhoc_holidays.append(pd.Timestamp('2005-11-24'))
        bDay.adhoc_holidays.append(pd.Timestamp('2006-11-23'))
        bDay.adhoc_holidays.append(pd.Timestamp('2007-11-22'))
        bDay.adhoc_holidays.append(pd.Timestamp('2008-11-27'))
        bDay.adhoc_holidays.append(pd.Timestamp('2009-11-26'))
        bDay.adhoc_holidays.append(pd.Timestamp('2010-11-25'))
        bDay.adhoc_holidays.append(pd.Timestamp('2011-11-24'))
        bDay.adhoc_holidays.append(pd.Timestamp('2012-11-22'))
        bDay.adhoc_holidays.append(pd.Timestamp('2013-11-28'))
        bDay.adhoc_holidays.append(pd.Timestamp('2014-11-27'))
        bDay.adhoc_holidays.append(pd.Timestamp('2015-11-26'))
        bDay.adhoc_holidays.append(pd.Timestamp('2016-11-24'))
        bDay.adhoc_holidays.append(pd.Timestamp('2017-11-23'))
        bDay.adhoc_holidays.append(pd.Timestamp('2018-11-22'))
        bDay.adhoc_holidays.append(pd.Timestamp('2019-11-28'))
        bDay.adhoc_holidays.append(pd.Timestamp('2020-11-26'))
        bDay.adhoc_holidays.append(pd.Timestamp('2021-11-25'))
        bDay.adhoc_holidays.append(pd.Timestamp('2022-11-24'))
        bDay.adhoc_holidays.append(pd.Timestamp('2023-11-23'))
        bDay.adhoc_holidays.append(pd.Timestamp('2024-11-28'))

**Comment by Stryder-Git** [comment]
The reason this isn't working is that `.adhoc_holidays` is not a regular attribute. It is actually a `property` -wrapped method, which will create a new list every time.

I also checked some of the dates in your appends, but they are all respected by .schedule...
```
nyse.schedule("2000-11-20", "2000-11-25")

                         market_open              market_close
2000-11-20 2000-11-20 14:30:00+00:00 2000-11-20 21:00:00+00:00
2000-11-21 2000-11-21 14:30:00+00:00 2000-11-21 21:00:00+00:00
2000-11-22 2000-11-22 14:30:00+00:00 2000-11-22 21:00:00+00:00 # no  '2000-11-23'
2000-11-24 2000-11-24 14:30:00+00:00 2000-11-24 18:00:00+00:00

nyse.schedule("2001-11-20", "2001-11-25")

                         market_open              market_close
2001-11-20 2001-11-20 14:30:00+00:00 2001-11-20 21:00:00+00:00
2001-11-21 2001-11-21 14:30:00+00:00 2001-11-21 21:00:00+00:00   # no '2001-11-22'
2001-11-23 2001-11-23 14:30:00+00:00 2001-11-23 18:00:00+00:0
``` 

So how to help you depends on what exactly you are trying to achieve.

If you think that some holidays are missing, could you be more specific about which ones and where they are not correctly respected?

If you are just interested in customizing holidays, you should consider something like this:

```
from pandas_market_calendars.exchange_calendar_nyse import NYSEExchangeCalendar

class MyNyse(NYSEExchangeCalendar):
    @property
    def adhoc_holidays(self):
        hols = super().adhoc_holidays
        hols.append("2001-11-21")
        return hols

mine = MyNyse()
mine.schedule("2001-11-20", "2001-11-25")
                         market_open              market_close
2001-11-20 2001-11-20 14:30:00+00:00 2001-11-20 21:00:00+00:00
2001-11-23 2001-11-23 14:30:00+00:00 2001-11-23 18:00:00+00:00

```

**Comment by nirvana1122** [comment]
@Stryder-Git thanks for the detailed example. I figured out what I was doing wrong. I was trying to create _CustomBusinessDay_ object by passing  it _pandas_market_cal as mcal.get_calendar()_  . Working on your example above I figured that I can directly get the _CustomBusinessDay_ object by calling _.holiday()_ method.
