### ISSUE TITLE
schedule() error with open_time_default

### ISSUE THREAD

**Issue by matthewgilbert** [rsheftel/pandas_market_calendars#17]
If I instantiate an implementation of a `MarketCalendar` which does not implement `open_time` and `close_time`, the `schedule` function throws errors. The issue is with the call to `days_at_time` by the `schedule` function, e.g.

```python
# `DatetimeIndex`s of standard opens/closes for each day.
opens = days_at_time(_all_days, self.open_time, self.tz, self.open_offset)
closes = days_at_time(_all_days, self.close_time, self.tz, self.close_offset)
```
Since `self.open_time = self.open_time_default = None`, this throws an `AttributeError` in `days_at_time`. A simple example is

```python
import pandas_market_calendars as mcal
import pandas as pd
from pandas.tseries.holiday import AbstractHolidayCalendar

class DummyCalendar(mcal.MarketCalendar):

    @property
    def name(self):
        return "Adhoc"

    @property
    def tz(self):
        return "UTC"

    @property
    def adhoc_holidays(self):
        return [pd.Timestamp("2015-01-03", tz="UTC")]

    @property
    def regular_holidays(self):
        return AbstractHolidayCalendar()


dummy = DummyCalendar()
dummy.schedule("2015-01-01", "2015-01-10")
```

Unless I'm missing something, my thoughts are that as it currently stands it seems like making `open_time` and `close_time` abstract methods would be better unless there is a default value that would address this?

**Comment by rsheftel** [comment]
Good catch. I just added open_time_default and close_time_default as abstract properties so that all new calendar classes must implement. New commit with tests here: 657cd34eea9abf73903afdcfee747c7fdc536e3a
