### ISSUE TITLE
IEX Integration

### ISSUE THREAD

**Issue by carterjfulcher** [rsheftel/pandas_market_calendars#181]
Any plans / blocks with adding integration for [IEX's](https://exchange.iex.io/) trading calendar? Haven't ever seen them deviate from NYSE but would be nice to have. 

If there are no objections I will submit a PR for this integration.

**Comment by glossner** [comment]
@carterjfulcher  - Thanks for opening this enhancement issue. 

Does the proposed PR replicate the entire NYSE calendar?

I took a quick look at [the trading hours](https://exchange.iex.io/resources/trading/trading-hours-holidays/). They are different than NYSE. However, if all the holidays are the same then it is probably best not to replicate the entire NYSE calendar.

**Comment by Stryder-Git** [comment]
I don't have any objections to it. In fact, if there aren't too many differences, inheriting from the NYSE Calendar may be the simplest option. Then you can just overwrite what doesn't fit.

**Comment by glossner** [comment]
@Stryder-Git I looked very briefly at doing something similar for the CME calendars. It wasn't clear to me if the calendar factory will recognize calendar names from derived classes.

**Comment by carterjfulcher** [comment]
> @Stryder-Git I looked very briefly at doing something similar for the CME calendars. It wasn't clear to me if the calendar factory will recognize calendar names from derived classes.

The calendar factory recognizes my new IEXExchangeCalendar just fine

**Comment by Stryder-Git** [comment]
> @Stryder-Git I looked very briefly at doing something similar for the CME calendars. It wasn't clear to me if the calendar factory will recognize calendar names from derived classes.

Is this not what you mean? It works for me...

```
import pandas_market_calendars as mcal

class MyTestCalendar(mcal.exchange_calendar_nyse.NYSEExchangeCalendar): # derived
    aliases = ["testcal"]
    
tst = mcal.get_calendar("testcal") # works with alias
tst.__class__
>> __main__.MyTestCalendar

nyse = mcal.get_calendar("NYSE") 
nyse.__class__
>> pandas_market_calendars.exchange_calendar_nyse.NYSEExchangeCalendar
```

Although, you do *need* an alias, otherwise it will override the parent class in the registry.

**Comment by glossner** [comment]
@Stryder-Git Thanks! Overriding aliases indeed works perfectly.

**Comment by carterjfulcher** [comment]
@glossner you're welcome
