### ISSUE TITLE
NYSE / NASDAQ 2021 XMas marked as closed.

### ISSUE THREAD

**Issue by zolt4n** [rsheftel/pandas_market_calendars#187]
the following code display NYSE and NASDAQ as close on XMAS.
python 3.9.4
pandas-market-calendars-3.4

```python3
def is_market_open(callandar_name:str, day:datetime.date):
    market = mcal.get_calendar(callandar_name)
    days = market.valid_days(start_date=day, end_date=day)
    open = len(days) == 1
    return open
```

**Comment by glossner** [comment]
@zolt4n Dec 25th 2021 was a Saturday. The market was closed. I'm inferring that date from your header. I'm going to mark this as closed but if you have a different date you believe is a bug please reopen it.

**Comment by zolt4n** [comment]
https://www.google.com/search?q=nyse+holidays+2021+christmas+eve&rlz=1C1GCEA_enUS964US964&ei=SG0mYtm7DJCaptQP8tS3SA&oq=nyse+holidays+2021&gs_lcp=Cgdnd3Mtd2l6EAMYAjIICAAQgAQQyQMyBQgAEIAEMgUIABCABDIFCAAQgAQyBQgAEIAEMgUIABCABDIFCAAQgAQyBQgAEIAEMgUIABCABDIFCAAQgAQ6CggAEEcQsAMQyQM6BwgAEEcQsAM6BwgAELADEEM6CggAEOQCELADGAA6EgguEMcBEK8BEMgDELADEEMYAToMCC4QyAMQsAMQQxgBOgoIABCxAxDJAxBDSgQIQRgASgQIRhgBUM8EWKYFYIUVaAFwAXgAgAFhiAG3AZIBATKYAQCgAQHIARHAAQHaAQYIABABGAnaAQYIARABGAg&sclient=gws-wiz 


indeed you're right. I looked at the code and understand the logic a bit more now.

Thanks for the quick update though.

**Comment by zolt4n** [comment]
On the other hand I tried the following dates and I get closed as well.

2023-07-04 for XNYSE is closed
2022-11-24 for XNYSE is closed
2023-11-23 for XNYSE is closed
2024-07-04 for XNYSE is closed
2024-11-28 for XNYSE is closed
2024-12-25 for XNYSE is closed

see for references: 
https://www.nyse.com/markets/hours-calendars

**Comment by glossner** [comment]
@zolt4n  yes. A couple of those should have been coded as early close. Not full day. The tests are wrong too.

I'll reopen the issue and try to get a fix in within a week or so. We also welcome pull requests!

Thanks.

**Comment by glossner** [comment]
@zolt4n  I've reviewed the calendar and tests again and believe it is coded correctly.

2022-11-24 The Market will be closed. The following day is early close at 1pm. This is coded and tested correctly. That is my interpretation of the footnote.

2023-07-04 The Market will be closed. The Monday before is early close at 1pm. This is also tested correctly.
2023-11-24 Same interpretation as 2022-11-24

2024 is not tested yet.

**Comment by zolt4n** [comment]
Hum indeed I think you are right.
Thanks for the quick review
