### ISSUE TITLE
ImportError: cannot import name 'BaseSelector' from 'selectors'

### ISSUE THREAD

**Issue by EmersonDove** [rsheftel/pandas_market_calendars#192]
Hey awesome library.

Our repo has a dependency on this library and one of our users is getting this error - just wanted to let you know about it:

![image-5](https://user-images.githubusercontent.com/52636744/165793315-ff9e59c4-4623-426f-8d28-4aed39b96f9b.png)

You can see we import pandas_market_calendars in utils. The pip install for the user finished successfully.

**Comment by ilCatania** [comment]
@EmersonDove is it possible your user has a `selectors.py` script somewhere in the pythonpath alongside the script he's running? That file may be shadowing the `selectors.py` module pandas_market_calendars relies on

**Comment by EmersonDove** [comment]
Oh thats a great theory, I will ask

**Comment by EmersonDove** [comment]
> @EmersonDove is it possible your user has a `selectors.py` script somewhere in the pythonpath alongside the script he's running? That file may be shadowing the `selectors.py` module pandas_market_calendars relies on

Looks like this was it. I'll close this.
