### ISSUE TITLE
mcal.get_calendar("NYSE").holidays() returns CustomBusinessDay

### ISSUE THREAD

**Issue by yarimiz** [rsheftel/pandas_market_calendars#194]
Hey,
I'm new to this library and trying to retrieve a list of holidays for NYSE, using the following code:
```
nyse = mcal.get_calendar("NYSE")
nyse.holidays()

<CustomBusinessDay>
```

The object I'm getting in return is CustomBusinessDay, not a list of days.

Am I missing something? My code is pretty simple and is similar to the examples of the library.

**Comment by ilCatania** [comment]
if you look closely at the examples, this works:
```python
import pandas_market_calendars as mcal

nyse = mcal.get_calendar("NYSE")
cal = nyse.holidays()
print(cal.holidays[:5])
```
