### ISSUE TITLE
CME Sunday market open causes late_opens() to mismatch

### ISSUE THREAD

**Issue by glossner** [rsheftel/pandas_market_calendars#195]
While writing some tests for CME Globex calendars, I noticed that late_opens() comes back with matches. This is probably due to the shift in time to Sunday not being accounted for in MarketCalendar.is_different(). 

This is my reminder to come back and fix this or update late_opens() in the CMEGlobexBaseCalendar class.

**Comment by Stryder-Git** [comment]
I am actually almost done with the Fixed Income Calendar and am going to try some things regarding the market times we mentioned. Changes for that may impact this issue, so you can also leave this to me and I will have it done in about a week.
