### ISSUE TITLE
eurex

### ISSUE THREAD

**Issue by kewlfft** [rsheftel/pandas_market_calendars#2]
I am trying to implement eurex but could not find a clear definition of their rules which seems to have changed for the past years. welcome if anyone has some more insight.

**Comment by rsheftel** [comment]
Looking at the Eurex site they have current and historical holiday calendars here:

http://www.eurexchange.com/exchange-en/trading/trading-calendar

**Comment by kewlfft** [comment]
Thanks that is what I use but haven't found a rule that works for all the years yet

**Comment by rsheftel** [comment]
If I find any more info I will pass along
