### ISSUE TITLE
NYSE calendar: Friday after Independence Day is not a half day in 2019

### ISSUE THREAD

**Issue by vassilios** [rsheftel/pandas_market_calendars#20]
The official holidays for NYSE website (see below) shows that the 4th of July 2019 is on a Thursday. Yet the following Friday is NOT a half day.

The `FridayAfterIndependenceDayExcept2013` rule should either be removed or modified from the NYSE calendar to reflect this.

https://www.nyse.com/markets/hours-calendars

**Comment by rsheftel** [comment]
Thanks for finding the error. Fixed in latest commit: 990f7a813ca4e7320d5d5ae5a83fbee15d7647b5
