### ISSUE TITLE
Changes to `exchange_calendars` in v4

### ISSUE THREAD

**Issue by maread99** [rsheftel/pandas_market_calendars#200]
I see you've been busy over here of late!

Just wanted to give you a heads up that `exchange_calendars` v4.0 should be released by end June and there may be changes that affect you.

The main changes in 4.0 are covered by the [notice](https://github.com/gerrymanoim/exchange_calendars#notices-all-change) at the top of the `exchange_calendars` readme. A fuller list can be found at [exchange_calendars #61](https://github.com/gerrymanoim/exchange_calendars/issues/61).

In particular, we're changing the timezone of sessions and times. On the upside they will now have the same representation as in `pandas_market_calendars` (i.e. sessions tz-naive, times UTC).

Any questions regarding 4.0, let me know via comments to this issue or to [exchange_calendars #61](https://github.com/gerrymanoim/exchange_calendars/issues/61).

Also, you might also be interested in the new [`market_prices`](https://github.com/maread99/market_prices) library which uses `exchange_calendars` to create meaningful OHLCV datasets.

Cheers
Marcus

**Comment by rsheftel** [comment]
Thank you for the heads up!

**Comment by maread99** [comment]
Released today.

NOTE: **4.0.1 is the earliest working release of v4** (version 4.0 will fail to import!)
