### ISSUE TITLE
May 30 2022 still appears in LSE exchange holiday calendar. 

### ISSUE THREAD

**Issue by jima-dad** [rsheftel/pandas_market_calendars#201]
With regards to [#130](https://github.com/rsheftel/pandas_market_calendars/issues/130), I found that May 30 2022 still appears in LSE holiday calendar. This year 2022 May 30th is not a bank holiday as we have Platinum Jubilee holidays.  

The example code is shown below;

```
import exchange_calendars as xcals

print('exchange_calendars.__version__ : ', xcals.__version__)

import pandas_market_calendars as mcal
from pandas.tseries.offsets import CustomBusinessHour, CustomBusinessDay, CBMonthEnd 

print('pandas_market_calendars.__version__ : ', mcal.__version__)

lse_exch = mcal.get_calendar('LSE')

print('LSE Holidays 2022')
list_lse_hol = hol_lse.holidays
list_lse_hol_2022 = list(filter(lambda x: pd.to_datetime(x).year == 2022,list_lse_hol ))
list_lse_hol_2022
```

and got the following result

```
exchange_calendars.__version__ :  3.6.3
pandas_market_calendars.__version__ :  3.4
LSE Holidays 2022
[numpy.datetime64('2022-01-03'),
 numpy.datetime64('2022-04-15'),
 numpy.datetime64('2022-04-18'),
 numpy.datetime64('2022-05-02'),
 **_numpy.datetime64('2022-05-30')_**,
 numpy.datetime64('2022-06-02'),
 numpy.datetime64('2022-06-03'),
 numpy.datetime64('2022-08-29'),
 numpy.datetime64('2022-12-25'),
 numpy.datetime64('2022-12-26'),
 numpy.datetime64('2022-12-27')]
```

Please take care

**Comment by ValueRaider** [comment]
Calendar 'XLON' from module `exchange_calendars` handles day correctly. Which raises question - why have calendar 'LSE' at all if it's (a) duplicate and (b) broken?

**Comment by rsheftel** [comment]
@ValueRaider , this package has it's own native calendars, but as a bonus feature it can also wrap the calendars in exchange_calendars. So you get to choose.

**Comment by jima-dad** [comment]
Hi @ValueRaider 

Thank you for your advise.
I got the correct result shown in below.

`mport pandas_market_calendars as mcal
from pandas.tseries.offsets import CustomBusinessHour, CustomBusinessDay, CBMonthEnd 

lse_exch = mcal.get_calendar('XLON')

print('LSE Holidays 2022')
list_lse_hol = lse_exch.holidays()

list_lse_hol_2020 = list(filter(lambda x: pd.to_datetime(x).year == 2020,list_lse_hol.holidays ))
print(list_lse_hol_2020)

list_lse_hol_2022 = list(filter(lambda x: pd.to_datetime(x).year == 2022,list_lse_hol.holidays ))
print(list_lse_hol_2022)
`
and outcomes are ;
`LSE Holidays 2022
[numpy.datetime64('2020-01-01'), numpy.datetime64('2020-04-10'), numpy.datetime64('2020-04-13'), numpy.datetime64('2020-05-08'), numpy.datetime64('2020-05-25'), numpy.datetime64('2020-08-31'), numpy.datetime64('2020-12-25'), numpy.datetime64('2020-12-26'), numpy.datetime64('2020-12-28')]
[numpy.datetime64('2022-01-03'), numpy.datetime64('2022-04-15'), numpy.datetime64('2022-04-18'), numpy.datetime64('2022-05-02'), numpy.datetime64('2022-06-02'), numpy.datetime64('2022-06-03'), numpy.datetime64('2022-08-29'), numpy.datetime64('2022-12-25'), numpy.datetime64('2022-12-26'), numpy.datetime64('2022-12-27')]`

Thank you so much!
Jima_dad
