### ISSUE TITLE
date_range cannot handle time zone aware schedules

### ISSUE THREAD

**Issue by tvr101** [rsheftel/pandas_market_calendars#209]
date_range is useful to generate intraday timestamps, but it assumes that the schedule passed to it does not have a time zone set. could this be made more flexible?

(see line 222 in calendar_utils.py: return pd.DatetimeIndex(time_series.drop_duplicates(), tz= "UTC") )

here is a snippet that replicates the error:

import pandas_market_calendars as mcal
nyse = mcal.get_calendar("NYSE")
df_schedule = nyse.schedule("2022-07-01", "2022-07-01", tz="America/Chicago")
mcal.date_range(df_schedule, frequency="1H")

**Comment by rsheftel** [comment]
This is fixed in v4.0
