### ISSUE TITLE
UK market holiday 2022-09-19

### ISSUE THREAD

**Issue by michaelcraig-quantinuum** [rsheftel/pandas_market_calendars#216]
Following the Queen's death, there is a UK Bank holiday declared for Monday September 19th 2022. The London Stock Exchange and others will be impacted and will require data updating

**Comment by ilCatania** [comment]
According to internet sources, the following ad hoc bank holidays are implemented:

UK: 19 September 2022 https://www.londonstockexchange.com/trade/trading-access/business-days
Australia: 22 September 2022 https://www2.asx.com.au/markets/market-resources/asx-24-trading-calendar
New Zealand: 26 September https://www.nzx.com/services/nzx-trading/hours-boards
Canada: 19 September but some provinces including Quebec/Ontario declined, for example TSE was open: https://www.tsx.com/trading/calendars-and-trading-hours/calendar

**Comment by ilCatania** [comment]
I've added UK and Australia, I've not seen an existing NZ holiday calendar in the codebase.

**Comment by Stryder-Git** [comment]
Thank you, @ilCatania !
