### ISSUE TITLE
Scheduling doesn't work over long time period

### ISSUE THREAD

**Issue by HStoneCreek** [rsheftel/pandas_market_calendars#218]
Hi guys,

first of all thanks for your amazing package!

As I'm using it mainly for backtesting purposes, I'm dealing with long time periods.
However, there seems to be an issue, when using the schedule function over an extended period.

See my code snippet below:

import pandas_market_calendars as mcal

nyse = mcal.get_calendar('NYSE')

print(mcal.get_calendar_names())

early = nyse.schedule(start_date='1980-01-01', end_date='2022-07-10')

Error message:
 temp.loc[specialix] = special
ValueError: cannot reindex on an axis with duplicate labels

Setup:
pandas_market_calendars==4.0
pandas==1.5.0
python 3.9

Any thoughts on this?
Thanks for your help in advance!

**Comment by Stryder-Git** [comment]
Hi, sorry about that.

There is actually already a fix, but it hasn't been pushed to pypi yet (we are in the process of overhauling the release management). Until then the best thing you can do is just cloning this repo, rather than installing with pip.

Does that work for now?

**Comment by HStoneCreek** [comment]
Yeah, that works. Thank you!
