### ISSUE TITLE
Register and enforce calendars by ISO 10383

### ISSUE THREAD

**Issue by timkpaine** [rsheftel/pandas_market_calendars#220]
The calendar registry should enforce adherence to https://www.iso20022.org/market-identifier-codes

Right now, it appears markets are largely registered by a common name or by their MIC, rather than their operating MIC. As an example, IEX is addressable by `IEX` rather than its mic `IEXG` or its operating mic `IEXG`. NYSE is registered under `['NYSE', 'stock', 'NASDAQ', 'BATS', 'DJIA', 'DOW']` but not `XNYS`. 

PR will follow shortly, in addition to `name` and `aliases` I will add `mic` / `operating mic` so that calendars can be fetched by their operating mic.

**Comment by rsheftel** [comment]
The reason for this is part legacy, and part the ability to use the calendars in the https://github.com/gerrymanoim/exchange_calendars project. Right now if you use an ISO name it will reach through to the exchange_calenders package and use those. Please take that workflow into consideration when making your PR. How to allow people that are currently using the exchange_calendars via the ISO to continue to do so? Or perhaps if this package has the calendar that overrides the exchange_calendar?

I am open to any solution, as long as it doesn't break things for users.
