### ISSUE TITLE
Warnings in Github Actions

### ISSUE THREAD

**Issue by Stryder-Git** [rsheftel/pandas_market_calendars#243]
This is a reminder to deal with the warnings raised in our CICD flow, which seem to be mostly these:

>run_tests / run_tests (windows-latest, 3.9)
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: coverallsapp/github-action@master. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.

>run_tests / run_tests (macos-latest, 3.10)
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by rsheftel** [comment]
Moved this to the wiki here: https://github.com/rsheftel/pandas_market_calendars/wiki/Warning-on-GitHub-Actions
