### ISSUE TITLE
Holiday error for CFE, juneteenth

### ISSUE THREAD

**Issue by dougransom** [rsheftel/pandas_market_calendars#261]
June 19 is not a valid trading day for CBOE but is showing as valid.

`>>> import pandas_market_calendars as mcal
>>> _cfe_calendar = mcal.get_calendar('CFE')
>>> _cfe_calendar.valid_days('2023-06-17','2023-06-20')
DatetimeIndex(['2023-06-19 00:00:00+00:00', '2023-06-20 00:00:00+00:00'], dtype='datetime64[ns, UTC]', freq='C')`

Reference https://cdn.cboe.com/resources/aboutcboe/Cboe-2023FuturesSettlementCalendar.pdf

version: pandas-market-calendars       4.1.4

**Comment by dougransom** [comment]
https://github.com/dougransom/vix_utils/issues/21

**Comment by rsheftel** [comment]
Fixed in 6f2b8c776bde67f00104c43847846dcc2bf39931

**Comment by dougransom** [comment]
Amazing.  Thanks!
