### ISSUE TITLE
Documentation Not Displaying Code Cells

### ISSUE THREAD

**Issue by cperotlsq** [rsheftel/pandas_market_calendars#262]
In the latest documentation at https://pandas-market-calendars.readthedocs.io/en/latest/usage.html#setup-new-exchange-calendar, it seems that the code cells are missing and it only shows the output cells. Here is an archived version of what it used to look like with the code cells: http://web.archive.org/web/20220719194459/https://pandas-market-calendars.readthedocs.io/en/latest/usage.html.

**Comment by rsheftel** [comment]
This is resolved
