### ISSUE TITLE
sdist for 4.2.0 is broken

### ISSUE THREAD

**Issue by timkpaine** [rsheftel/pandas_market_calendars#267]
Does not include python assets

<img width="248" alt="Screenshot 2023-08-21 at 10 59 35" src="https://github.com/rsheftel/pandas_market_calendars/assets/3105306/4dbbb84a-f5a3-4cb0-b413-12b09972e52b">

Broken in https://github.com/rsheftel/pandas_market_calendars/pull/266/

**Comment by CYLEE21** [comment]
Same problem here, is this bug fixed in the most recent version?

**Comment by rsheftel** [comment]
v.4.2.1 fixes this
