### ISSUE TITLE
source tarball for Linux package

### ISSUE THREAD

**Issue by kewlfft** [rsheftel/pandas_market_calendars#27]
Hello @rsheftel 

I wish to make an **_Arch Linux_** package for `pandas_market_calendars`. Would you be able to save the source tarball whenever you make a Python wheel ? 
Usually a source tarball is available in pypi but not for `pandas_market_calendars`,

This is typically where I would pickup the source [here](https://pypi.python.org/simple/pandas-market-calendars/) but there are only _.whl_

Alternatively, if you prefer I can pick up releases you would make on GitHub.

Thanks

**Comment by rsheftel** [comment]
Done. source tarball upload now along with wheel.

**Comment by kewlfft** [comment]
Thanks ! if you can continue to do it going forward so that I can update the Arch package whenever there is a new version. Do you want to mention somewhere that a Linux package exists?
