### ISSUE TITLE
Arch Linux Package

### ISSUE THREAD

**Issue by kewlfft** [rsheftel/pandas_market_calendars#28]
1. if you can continue to provide the source going forward so that I can update the Arch package whenever there is a new version. Do you want to mention somewhere that a Linux package exists? [Package_AUR](https://aur.archlinux.org/packages/python-pandas_market_calendars/)
2. the `toolz` package is causing me some issues because it is not in the official Linux repository. Is it really a requirement ? I see it is used in example but the market_calendar does not seem to require it. Can you confirm? Note that I created the package without this requirement and tested it with a few examples and it worked fine.

**Comment by rsheftel** [comment]
Question... when I install packages on linux (Ubuntu) I just use pip and it seems to work fine with the wheel files. How is this tarball different? I am happy to promote the existence of the Arch Linux package, but want to make sure I understand exactly what that means.

Looks like you are correct on the toolz I removed in the latest commit ec34bfce86a87da6da2a984e44d006e7c0177703

**Comment by kewlfft** [comment]
`pip` is ok and I was using it till now for pandas_market_calendars. Then:
1. it is not very good at managing dependencies, updates and removal with dependencies
2. it also means you need to manage separately your Linux distro packages and your python packages. In Arch we usually create our python packages, then everything is properly managed and updated in the same place. The package is created from the source, we use setuptools and execute python setup.py build/install.

Note that Arch is now the #1 distro as ranked by distrowatch [here](https://distrowatch.com/index.php?dataspan=4) : Manjaro is an Arch based distro - Antergos as well not far behind.

**Comment by rsheftel** [comment]
Thanks for the explanation, very interesting. How do you suggest I advertise this fact? Include in the README.rst? Is there a standard way to state "go here for Arch Linux package"

In terms of release I added the tarball to the process so should be on PyPi for all future releases.

**Comment by kewlfft** [comment]
Great, yes I think the link in the README would be fine. 
Thanks very much.

**Comment by rsheftel** [comment]
Done. thanks.
