### ISSUE TITLE
ModuleNotFoundError with pandas-2.1.0 and pandas-market-calendars-4.3.0

### ISSUE THREAD

**Issue by shuanang** [rsheftel/pandas_market_calendars#289]
With the latest pandas-2.1.0 and pandas-market-calendars-4.3.0, 

`import pandas_market_calendars as mcal`
`# Create a calendar`
`nyse = mcal.get_calendar('NYSE')`
`# Show available calendars`
`print(mcal.get_calendar_names())`

I get the following error:

> Traceback (most recent call last):
>   File "/Users/angyishuan/Dropbox/test24.py", line 183, in <module>
>     import pandas_market_calendars as mcal
>   File "/Users/angyishuan/miniconda/envs/tf-metal/lib/python3.11/site-packages/pandas_market_calendars/__init__.py", line 19, in <module>
>     from .calendar_registry import get_calendar, get_calendar_names
>   File "/Users/angyishuan/miniconda/envs/tf-metal/lib/python3.11/site-packages/pandas_market_calendars/calendar_registry.py", line 2, in <module>
>     from .calendars.asx import ASXExchangeCalendar
> ModuleNotFoundError: No module named 'pandas_market_calendars.calendars'

I reverted back to pandas-market-calendars-4.2.1 and pandas-2.0.3 and the problem does not occur. Please advise, thanks!

**Comment by davidlatte** [comment]
Confirmed.  I also see this issue with the latest 4.3.0 release on both Windows and Linux machines.
