### ISSUE TITLE
Missing Comma in Energy and Metals Aliases List

### ISSUE THREAD

**Issue by cperotlsq** [rsheftel/pandas_market_calendars#295]
Hello,

It looks like there's a missing comma in the definition of `aliases` [here](https://github.com/rsheftel/pandas_market_calendars/blob/810e29bd9e343d0e35168214cc80683d4d8c203f/pandas_market_calendars/calendars/cme_globex_energy_and_metals.py#L88), more specifically, I believe there should be a comma between these two strings:
```
'CMEGlobex_Silver' 'CMEGlobex_SI'
```

Regards,
Cameron

**Comment by rsheftel** [comment]
Fixed. Thank you
