### ISSUE TITLE
missing data for dates prior to 1995-01-01

### ISSUE THREAD

**Issue by roy-themachine** [rsheftel/pandas_market_calendars#296]
It seems that the library doesn't support dates prior to 1995, is that a know limitation?
Are there any plans to support past days?

**Comment by rsheftel** [comment]
Are you speaking of any particular calendar? Many go back will before 1995.

**Comment by roy-themachine** [comment]
Oh sorry, yes I mean NYSE (New York stock exchange)Thanks,Roy MoshkovitzOn Sep 24, 2023, at 10:06 PM, rsheftel ***@***.***> wrote:﻿
Are you speaking of any particular calendar? Many go back will before 1995.

**Comment by glossner** [comment]
pandas_market_calendars/calendars/nyse.py goes back to 1885.
