### ISSUE TITLE
XNSE 2023-06-29 missing holiday

### ISSUE THREAD

**Issue by npezolano** [rsheftel/pandas_market_calendars#300]
2023-06-29 should be a holiday for XNSE called Bakri Id, currently 2023-06-28 is incorrectly listed as a holiday.

https://www.nseindia.com/resources/exchange-communication-holidays

![image](https://github.com/rsheftel/pandas_market_calendars/assets/1518637/6479abf6-9f66-486d-bd1a-ce9aab514f5f)

**Comment by rsheftel** [comment]
Fixed
