### ISSUE TITLE
date_range 1min ranges from 9:31am to 4pm instead of 9:30am to 3:59pm

### ISSUE THREAD

**Issue by abquantfactor** [rsheftel/pandas_market_calendars#304]
I am using version 4.3.1 with pandas 2.0.3.

<img width="673" alt="CleanShot Cursor 2023-11-14 at 104552@2x" src="https://github.com/rsheftel/pandas_market_calendars/assets/74194197/614fe3bf-6a22-4eae-bdcd-0d0cdd865489">

The following code results in a range from 9:31am til 4:00pm instead of 9:30am til 3:59pm.

Can I somehow change this behaviour? Is it intended? 

Of course, I can subtract 1 minute from every entry. I am just looking for a better way.

**Comment by rsheftel** [comment]
That is the intended behavior. The timestamp on the bar represents the time at the end of the bar. So the first 1min bar of the trading day goes from 9:30am to 9:31am, so the timestamp is 9:31am.

**Comment by abquantfactor** [comment]
I would disagree and say the first bar usually goes from 9:30:00 until
9:30:59 and the second one starts at 9:31:00am. But OK, if this is
intended, I will just subtract a timedelta of 1 minute.

Thanks

**Comment by maread99** [comment]
FWIW, you can get the index you're after from the [exchange_calendars](https://github.com/gerrymanoim/exchange_calendars) calendar which is (I believe) the source of the data for the 'XNYS' schedule...

```python
import exchange_calendars as xcals
cal = xcals.get_calendar("XNYS")
index = cal.trading_index(
    "2010-01-04",
    "2023-10-31",
    "1T",
    intervals=False,
    closed="left"
).tz_convert("US/Eastern")
```
Here the 'close' parameter effectively lets you choose which side of the bar you want to represent. Takes from:
- 'left' (default) gives you what you're after
- 'right' would give you what you were getting 
- 'both' will include both the 09:00 and 16:00 minutes
- 'neither' will exclude both the 09:00 and 16:00 minutes
