### ISSUE TITLE
Wondering about trading hours

### ISSUE THREAD

**Issue by kovkev** [rsheftel/pandas_market_calendars#31]
Hi,

I'm looking to trade and need to know when are exchanges open. I think I will move forward with this library. 

One issue I have is that it doesn't have trading hours of NASDAQ (but it does have NYSE). I am comparing the trading hours and holidays of NASDAQ and NYSE and they seem very similar. Also, when I check on

https://www.worldtimezone.com/markets24.php

, I see that they do not show NASDAQ (I don't know how to understand DFIX, NASDAQ Dubai), but they do show NYSE.

##### Are NYSE's and NASDAQ's trading hours the same? Or almost the same? Where would be a better place to ask this?

Also, this library does not tell you what the pre-market and after market hours are.

##### Is there any way to know the pre-market and after market hours if you're given the regular trading hours? Is it always a certain numbers of hours before market open and and a certain number of hours after close?

Thank you,

kovkev

**Comment by rsheftel** [comment]
Are NYSE's and NASDAQ's trading hours the same? Or almost the same? Where would be a better place to ask this?

Yes. All equities exchanges in the US follow the same schedule, and as a tradition the NYSE sets that schedule. You can confirm the holidays for NASDAQ and the market hours here:

https://www.nasdaq.com/article/what-time-does-the-stock-market-open-and-close-cm619778
https://www.nasdaqtrader.com/Trader.aspx?id=Calendar

Is there any way to know the pre-market and after market hours if you're given the regular trading hours? Is it always a certain numbers of hours before market open and and a certain number of hours after close?

The above link also has information on the extended hours trading for NASDAQ. For NYSE there is info here:

https://www.nyse.com/markets/hours-calendars
https://en.wikipedia.org/wiki/Extended-hours_trading

**Comment by kovkev** [comment]
Hi rsheftel,

Thank you for the clear answer on the first point.

Do the pre-market and after-market hours run (are open) if on that day the exchange was closed during regular trading hours?

**Comment by rsheftel** [comment]
I dont believe that pre and after hours are open if the market is closed, bit you should check that with the exchange web sites
