### ISSUE TITLE
Juneteenth not added to the listed holidays in cme.py

### ISSUE THREAD

**Issue by K-m-Ye** [rsheftel/pandas_market_calendars#335]
Hi all,

Juneteenth is now on the holiday calendar for a lot of the major US exchanges. See below:

https://www.cmegroup.com/tools-information/holiday-calendar.html
https://www.ice.com/publicdocs/futures_us/exchange_notices/ICE_Futures_US_ExNot2024_Holidays_20230810.pdf
https://www.nyse.com/markets/hours-calendars

I believe most of the major US Holidays are covered in the package with the exception of Juneteenth. I'm happy to maybe write my own solution to this, but wanted to post here to see if people were already working on a solution.

Thanks!

**Comment by glossner** [comment]
@K-m-Ye  which specific calendars are you not seeing them in? Juneteenth is coded in nyse and cme. Do you have a test case where you aren't seeing them in the holidays list? Make sure you have the latest version of pandas_market_calendars installed. Thanks.

**Comment by glossner** [comment]
cme.py is a legacy calendar that would be appreciated to receive a pull request from anyone still using it.

cme_globex_base.py and the corresponding instantiated classes do contain Junteenth for products that observe it. It  is also possible some of them have changed observance. 

I'm closing this issue but feel free to reopen it if there are additional questions.

**Comment by glossner** [comment]
I changed the title and I'm re-opening this because cme.py doesn't have Juneteenth. If anyone is using that calendar, please feel free to submit a pull request. Thanks.
