### ISSUE TITLE
Victoria Day

### ISSUE THREAD

**Issue by innominate227** [rsheftel/pandas_market_calendars#34]
2015-05-25 and 2009-05-25 in TSX are treated as Victoria day.  However 2015-05-18 and 2009-05-18 are the correct dates.

**Comment by rsheftel** [comment]
@gabalese since you did the Japanese calendars, is this change requested correct?

**Comment by gabalese** [comment]
I think @innominate227 means the Toronto Stock Exchange.

**Comment by rsheftel** [comment]
@gabalese  good catch, sorry about that. OK, @innominate227 that code came from the original Quantopian that I forked. Can you send me a link to some web page that shows the correct dates and I will see why the logic is wrong and correct. Also if you have the time you could submit a pull request.

**Comment by innominate227** [comment]
Here is a calendar showing Victoria day:
https://www.timeanddate.com/holidays/canada/2015
https://www.timeanddate.com/holidays/canada/2009

Here is a fixed implementation:
`import numpy as np
from dateutil.relativedelta import MO
from pandas.tseries.holiday import AbstractHolidayCalendar, Holiday
from pandas.tseries.offsets import DateOffset
from pandas_market_calendars.exchange_calendar_tsx import VictoriaDay

class CalendarTest1(AbstractHolidayCalendar):  
    rules = [VictoriaDay]

class CalendarTest2(AbstractHolidayCalendar):  
    rules = [Holiday('Victoria Day', month=5, day=24, offset=DateOffset(weekday=MO(-1)))]



holidays1 = CalendarTest1().holidays()
holidays2 = CalendarTest2().holidays()

holidays1_unique = np.setdiff1d(holidays1, holidays2)
holidays2_unique = np.setdiff1d(holidays2, holidays1)`

**Comment by rsheftel** [comment]
Fixed in commit 346309e6db1429443cd57205bbe3b5d1996b851f
