### ISSUE TITLE
minimal version requirement

### ISSUE THREAD

**Issue by lp9052** [rsheftel/pandas_market_calendars#341]
I see the latest version requirement is python >= 3.9, is there any specific reason that we drop the support on 3.8?

We still have quite a lot applications run on 3.8. We'd like to see some transition time if possible.

**Comment by rsheftel** [comment]
Fair suggestion. I will change the min required python to 3.8 in the next release. I only test 3.9+ but I am sure it will work fine in 3.8

**Comment by rsheftel** [comment]
This is done in v4.1.1
