### ISSUE TITLE
24/7 Calendar is actually 24/5

### ISSUE THREAD

**Issue by jack-of-some-trades** [rsheftel/pandas_market_calendars#345]
Trying to implement this library into a Trading View like application. I'm looking to have capability to handle crypto markets in addition to others hence the need for the 24/7 Calendar. While testing stuff I ran into this fun little bug:

![Screenshot 2024-06-07 185329](https://github.com/rsheftel/pandas_market_calendars/assets/156244519/b7509582-f4f9-443b-ba8d-4e778695d1cf)

The weekend days, 07-07 & 07-08, are missing in that image. This boils down to the calendar adopting the default 5 Day Weekmask property of MarketCalendar (MarketCalendar.weekmask). 

I dug into the code a bit to figure out what is going wrong. It turns out the 7 day week is correctly defined in "exchange_calendars > always_open.py" as weekmask = "1111111". The problem is this property is not transferred from the "AlwaysOpenCalendar" to the "24/7ExchangeCalendar" class that is actually used by the library. 

pandas_market_calendars: Version 4.4.0
Python: Version 3.12.2

**Comment by rsheftel** [comment]
Fixed with v4.4.1

Thank you for the PR
