### ISSUE TITLE
Aliases not picking up holidays

### ISSUE THREAD

**Issue by npezolano** [rsheftel/pandas_market_calendars#347]
My understanding is these two aliases HKEX/XHKG should be the same https://github.com/gerrymanoim/exchange_calendars/blob/588ae13d38b96999243f3aa79ef2278f20a626b0/exchange_calendars/calendar_utils.py#L148

Not sure what's causing this using the latest code on the dev branch I'm seeing the following: 

```
cal = mcal.get_calendar('HKEX')
cal.schedule('2023-09-01', '2023-09-09')
```

![image](https://github.com/rsheftel/pandas_market_calendars/assets/1518637/08dcbf62-7f02-4d37-ab6e-4acb5168c26d)

```
cal = mcal.get_calendar('XHKG')
cal.schedule('2023-09-01', '2023-09-09')
```

![image](https://github.com/rsheftel/pandas_market_calendars/assets/1518637/34fbe5aa-117e-450a-a4bc-4081aca7b50a)

**Comment by npezolano** [comment]
It looks like the `adhoc_holidays` property is only being called for `HXEX`

**Comment by rsheftel** [comment]
This packages offers two sources for exchange calendars. Native to this package calendars are coded in this repo and listed here: https://pandas-market-calendars.readthedocs.io/en/latest/calendars.html#equity-market-calendars

HKEX is a native calendar and using that alias will use the code in this repo for the calendar.

The other source of calendars is https://github.com/gerrymanoim/exchange_calendars, as documented here: https://pandas-market-calendars.readthedocs.io/en/latest/calendars.html#exchange-calendars-package

XHKG is from that package.

When possible I recommend using the native calendars.
