### ISSUE TITLE
How to create a market schedule for a given day, on that day?

### ISSUE THREAD

**Issue by Ice101781** [rsheftel/pandas_market_calendars#37]
I have no problem determining opens\closes for a range of dates in the future, but if the parameters of my query using the .schedule() method are 'start_date=today, end_date=today', an error's raised when the code compiles involving self.tz : 'already tz-aware, use tz_convert'. Is there another way to determine if, say, the NYSE is open *right now*? Thanks in advance for any help with this.

**Comment by rsheftel** [comment]
You could use the valid_days() function and provide todays date for both the start and end date. If today is valid then the date will show in the returned list, if not the list will have length of zero. This will work for the date, not if you are asking about a specific time after the close. Hope this gets you what you need.

**Comment by Ice101781** [comment]
That's a good suggestion, but I don't think I wasn't specific enough - I need to know the markets' status (open or closed) on non-regular days, when the markets are open for business, but close early - i.e., the Friday after Thanksgiving in the US. Is it possible to get that info *that day*?

**Comment by rsheftel** [comment]
The .schedule() method will return the error you got if the date you are requesting is not a valid trading day. So I would recommend first using the .valid_days() method to see if today() is a valid_days, then if so use the .schedule() method to find the times. The error you are getting is when there are no valid trading dates between the start and end parameters provided to the schedule() method.

**Comment by Ice101781** [comment]
Nice spot - I think that did the trick. I appreciate the help!
