### ISSUE TITLE
Feature request: calendar registration by metaclass

### ISSUE THREAD

**Issue by woutdenolf** [rsheftel/pandas_market_calendars#43]
Calendar registration is currently done by modifying "calendar_utils._calendars". This could be handled automatically with metaclasses. It would look something like this:

    class RegisterMeta(type):
        """Takes care of calendar registration
        """
    
    MarketCalendarMeta = type('MarketCalendarMeta', (ABCMeta, RegisterMeta), {})
    
    class MarketCalendar(six.with_metaclass(MarketCalendarMeta)):
        """Inherits from MarketCalendarMeta instead of ABCMeta, no other changes
        """
        
    get_calendar = MarketCalendar.calendar_factory
    calendars = list(MarketCalendar.calendar_class_registry.keys())

The only change is that MarketCalendar has a different metaclass. Additionally the derived calendars will have an "aliases" attribute:

    class NYSEExchangeCalendar(MarketCalendar):
        aliases = ['NYSE','NASDAQ','BATS']
        ....
    
    class CMEExchangeCalendar(MarketCalendar):
        aliases = ['CME','COMEX','CBOT','NYMEX']
        ....
    
Usage:

    print(calendars)
    ['MarketCalendar', 'NYSEExchangeCalendar', 'NYSE', 'NASDAQ', 'BATS', 'CMEExchangeCalendar', 'CME', 'COMEX', 'CBOT', 'NYMEX']
    
    mcal = get_calendar('NYSE',...)

You can use class name or alias to generate a calendar. One could consider removing "MarketCalendar" from the registry (will be there by default because it derives from RegisterMeta). Would you consider a PR that implements this idea?

**Comment by rsheftel** [comment]
Thanks for taking the time to explore this idea. I would absolutely consider a PR that implements this. I would just ask that you make sure all the current tests pass and if you can think of new tests that will make sure this functionality does not break in the future that would be great as well. Looking forward to it.

**Comment by rsheftel** [comment]
Thanks for the PR, it has been merged and I will release the new version to PYPI
