### ISSUE TITLE
Question: market open on regular holidays

### ISSUE THREAD

**Issue by woutdenolf** [rsheftel/pandas_market_calendars#44]
Is there a way to create a market calendar with opening days on regular holidays (the opposite of adhoc_holidays)? I was adding a custom calendar which has following irregularities: (https://www.ecb.europa.eu/press/pr/date/1999/html/pr990715_1.en.html)

- Open on Good Friday   1999-04-02 
- Open on Easter Monday 1999-04-05

I added Good Friday and Easter Monday to the regular holidays, but I would need an exception for the year 1999. Any suggestions?

**Comment by rsheftel** [comment]
I think the best way to do this would be to great a new holiday, like "Good_Friday_ECB", that is a derivative of the base holiday and have the Holiday function itself know that one date is excluded and do that at the Holiday level. I can not think of a good way otherwise to add back in holiday.

**Comment by woutdenolf** [comment]
Makes sense do create custom holidays. I ended up modifying the Holiday class to allow custom filters:

    class FilteredHoliday(Holiday):

        def __init__(self,*args,filter=None,**kwargs):
            super(FilteredHoliday,self).__init__(*args,**kwargs)
            self._filter = filter

        def _apply_rule(self, dates):
            """
            Args:
                dates(DateTimeIndex)
            Returns:
                DateTimeIndex
            """
            dates = super(FilteredHoliday,self)._apply_rule(dates)
            if self._filter:
                dates = self._filter(dates)
            return dates

Not fit for production (overriding hidden function) but it works. Used it as follows:

    GoodFridayMod = FilteredHoliday(
        "Good Friday",
        month=1,
        day=1,
        offset=[Easter(), Day(-2)],
        filter=wo1999
    )

    def wo1999(dates):
        """
        Args:
            dates(DateTimeIndex)
        Returns:
            DateTimeIndex
        """
        return dates[dates.year!=1999]

**Comment by rsheftel** [comment]
Seems like a smart solution... Did you want to commit that as a PR? Did you use it to create a new calendar you think others would benefit from?
