### ISSUE TITLE
Bug/Question about .convert_freq() and NYSE Sep 04

### ISSUE THREAD

**Issue by Busteren** [rsheftel/pandas_market_calendars#47]
Hi, this is the first time I am using this library, so not unlikely I am just doing something wrong. Anyway, I am trying to get the end and start of the NYSE for each month in 2018. Then the following code seems to me to be a bit odd behaviour. It will correctly return 4 September as the start date, however, with .convert_freq() it will start on the 3 Sep:
```
import pandas_market_calendars as mcal

early = nyse.valid_days(start_date='2018-07-01', end_date='2018-10-10')
early
DatetimeIndex(['2018-07-02', '2018-07-03', '2018-07-05', '2018-07-06',
               '2018-07-09', '2018-07-10', '2018-07-11', '2018-07-12',
               '2018-07-13', '2018-07-16', '2018-07-17', '2018-07-18',
               '2018-07-19', '2018-07-20', '2018-07-23', '2018-07-24',
               '2018-07-25', '2018-07-26', '2018-07-27', '2018-07-30',
               '2018-07-31', '2018-08-01', '2018-08-02', '2018-08-03',
               '2018-08-06', '2018-08-07', '2018-08-08', '2018-08-09',
               '2018-08-10', '2018-08-13', '2018-08-14', '2018-08-15',
               '2018-08-16', '2018-08-17', '2018-08-20', '2018-08-21',
               '2018-08-22', '2018-08-23', '2018-08-24', '2018-08-27',
               '2018-08-28', '2018-08-29', '2018-08-30', '2018-08-31',
               '2018-09-04', '2018-09-05', '2018-09-06', '2018-09-07',
               '2018-09-10', '2018-09-11', '2018-09-12', '2018-09-13',
               '2018-09-14', '2018-09-17', '2018-09-18', '2018-09-19',
               '2018-09-20', '2018-09-21', '2018-09-24', '2018-09-25',
               '2018-09-26', '2018-09-27', '2018-09-28', '2018-10-01',
               '2018-10-02', '2018-10-03', '2018-10-04', '2018-10-05',
               '2018-10-08', '2018-10-09', '2018-10-10'],
              dtype='datetime64[ns, UTC]', freq='C')

mcal.convert_freq(early, frequency='BMS')
DatetimeIndex(['2018-07-02', '2018-08-01', '2018-09-03', '2018-10-01'], dtype='datetime64[ns, UTC]', freq='BMS')
```
Is this how it should behave?
If not, then I would appreciate a workaround :)

**Comment by Busteren** [comment]
Okay, so I checked the implementation and it works as supposed for lower frequencies (which is what the documentation says).
Found that this works:
`pd.bdate_range('2018-07-01', '2018-10-10', freq='CBMS', holidays=nyse.holidays().holidays)`

Don't necessarily think it is worth changing the method, so can probably close issue? But will leave open for any of the mods to have a look.

**Comment by rsheftel** [comment]
Thanks for your feedback. That function was only intended to move to lower frequencies, but we will leave this open in case someone wants to submit a PR to make it work on longer durations as well.
