### ISSUE TITLE
CME schedule return error

### ISSUE THREAD

**Issue by bryanfok** [rsheftel/pandas_market_calendars#5]
I was testing the schedule method with CME market. 

`schedule = cme.schedule(start_date='2016-12-30', end_date='2017-01-10')`

And it return error 
`AttributeError: 'Index' object has no attribute 'tz_localize'`

**Comment by bryanfok** [comment]
`# with early closes
early = nyse.schedule(start_date='2012-07-01', end_date='2012-07-10')
early`

**Comment by rsheftel** [comment]
Something odd going on, will investigate

**Comment by bryanfok** [comment]
for CME, calendar type from `holidays_at_time` method return `Index([], dtype='object')`

**Comment by rsheftel** [comment]
I see the issue, I believe I have it fixed just making some tests now and will commit.

**Comment by rsheftel** [comment]
Bug fixed and new version committed. Thanks for finding this error.
