### ISSUE TITLE
GLOBEX closed from 5pm to 6pm

### ISSUE THREAD

**Issue by jperkins909** [rsheftel/pandas_market_calendars#50]
how come CME NYMEX show as open between 5-6pm EST? they don't trade 24 hours a day as the schedule suggests but 22 hours and 45 minutes a day, with pauses at 4:15 to 4:30 EST and 5pm-6pm EST

**Comment by rsheftel** [comment]
The futures have had less work done on them than the equity exchanges. Currently there is one generic class for all CME futures exchanges (including NYMEX) in this class here 
        pandas_market_calendars/pandas_market_calendars/exchange_calendar_cme.py
 You will see there is a generic open and close time.

If you would like to create a new specific NYMEX class and submit a PR that would be great.

**Comment by rsheftel** [comment]
As of the new v1.4 https://github.com/rsheftel/pandas_market_calendars/releases/tag/1.4 futures products are properly handled and can now have explicit calendars for each product type.
