### ISSUE TITLE
Version 0.21 has no calendars

### ISSUE THREAD

**Issue by xuxiao2695** [rsheftel/pandas_market_calendars#56]
```
import pandas_market_calendars as mcal
print(mcal.get_calendar_names())
```
It prints an empty array.

`nyse = mcal.get_calendar('NYSE')`
produces the error:
`RuntimeError: Class NYSE is not one of the registered classes: dict_keys(['MarketCalendar'])`

**Comment by rsheftel** [comment]
Please install the patched version 0.21a available here and on PyPi which fixes the issue
