### ISSUE TITLE
ICE and CME were open on 2018-12-05 National Day of Mourning

### ISSUE THREAD

**Issue by lhjensen** [rsheftel/pandas_market_calendars#57]
ICE US and CME were both open for commodity market trading on Wed, Dec 5 even though NYSE was closed for the National Day of Mourning for GHW Bush.

**Comment by rsheftel** [comment]
Thanks for this feedback. Right now the CME and ICE calendars are generic for all products. At some point in the future I may refactor into product specific calendars.

**Comment by mgellman-radix** [comment]
Since not all products were closed I'd vote this not be flagged as a holiday for the venue.

**Comment by rsheftel** [comment]
As of the new v1.4 https://github.com/rsheftel/pandas_market_calendars/releases/tag/1.4 futures products are properly handled and can now have explicit calendars for each product type.

**Comment by rsheftel** [comment]
Since we now have product specific calendar functionality I am going to close this issue. If there are specific calendars you would like to create to modify please let me know.
