### ISSUE TITLE
Cannot generate trading calendar after 2018-11-23 (Thanksgiving Friday holiday) #Bug

### ISSUE THREAD

**Issue by jordanxzz** [rsheftel/pandas_market_calendars#59]
Using the latest version **0.21.1** of the package, there is a problem retrieving the trading calendar after 2018-11-23 on a Linux server. The Python version on the server is Python 3.6.8 with Anaconda custom (64-bit).

`import pandas_market_calendars as mcal`
`nyse = mcal.get_calendar('NYSE')`
`schedule = nyse.schedule('2018-11-01','2018-11-30')`

The error message:
/usr/local/anaconda3/lib/python3.6/site-packages/pandas_market_calendars/market_calendar.py:397: FutureWarning: in the future, boolean array-likes will be handled as a boolean array index
  opens_or_closes.values[indexer] = special_opens_or_closes.values[good_indexes]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/anaconda3/lib/python3.6/site-packages/pandas_market_calendars/market_calendar.py", line 237, in schedule
    _overwrite_special_dates(_all_days, closes, _special_closes)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/pandas_market_calendars/market_calendar.py", line 397, in _overwrite_special_dates
    opens_or_closes.values[indexer] = special_opens_or_closes.values[good_indexes]
IndexError: index 1 is out of bounds for axis 1 with size 1

I checked several date interval input combinations and found that it is the date 2018-11-23 that brings the problem. Before that, everything works just fine but it breaks down on or after that day. It seems the code fails where the program tries to overwrite the special dates after getting a general business calendar.

Wonder if anyone could help. Thanks!

**Comment by rsheftel** [comment]
I am not able to replicate your error. With a clean install of python I get the following proper functionality. What is your pandas version, perhaps that is causing an issue. The version in my example below is 0.22

```
Python 3.4.3 (default, Sep 14 2016, 12:36:27) 
Type "copyright", "credits" or "license" for more information.

IPython 1.2.1 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import pandas_market_calendars as mcal

In [2]: mcal.__version__
Out[2]: '0.21.1'

In [3]: nyse = mcal.get_calendar('NYSE')

In [4]: schedule = nyse.schedule('2018-11-01','2018-11-30')

In [5]: schedule
Out[5]: 
                         market_open              market_close
2018-11-01 2018-11-01 13:30:00+00:00 2018-11-01 20:00:00+00:00
2018-11-02 2018-11-02 13:30:00+00:00 2018-11-02 20:00:00+00:00
2018-11-05 2018-11-05 14:30:00+00:00 2018-11-05 21:00:00+00:00
2018-11-06 2018-11-06 14:30:00+00:00 2018-11-06 21:00:00+00:00
2018-11-07 2018-11-07 14:30:00+00:00 2018-11-07 21:00:00+00:00
2018-11-08 2018-11-08 14:30:00+00:00 2018-11-08 21:00:00+00:00
2018-11-09 2018-11-09 14:30:00+00:00 2018-11-09 21:00:00+00:00
2018-11-12 2018-11-12 14:30:00+00:00 2018-11-12 21:00:00+00:00
2018-11-13 2018-11-13 14:30:00+00:00 2018-11-13 21:00:00+00:00
2018-11-14 2018-11-14 14:30:00+00:00 2018-11-14 21:00:00+00:00
2018-11-15 2018-11-15 14:30:00+00:00 2018-11-15 21:00:00+00:00
2018-11-16 2018-11-16 14:30:00+00:00 2018-11-16 21:00:00+00:00
2018-11-19 2018-11-19 14:30:00+00:00 2018-11-19 21:00:00+00:00
2018-11-20 2018-11-20 14:30:00+00:00 2018-11-20 21:00:00+00:00
2018-11-21 2018-11-21 14:30:00+00:00 2018-11-21 21:00:00+00:00
2018-11-23 2018-11-23 14:30:00+00:00 2018-11-23 18:00:00+00:00
2018-11-26 2018-11-26 14:30:00+00:00 2018-11-26 21:00:00+00:00
2018-11-27 2018-11-27 14:30:00+00:00 2018-11-27 21:00:00+00:00
2018-11-28 2018-11-28 14:30:00+00:00 2018-11-28 21:00:00+00:00
2018-11-29 2018-11-29 14:30:00+00:00 2018-11-29 21:00:00+00:00
2018-11-30 2018-11-30 14:30:00+00:00 2018-11-30 21:00:00+00:00

```

**Comment by jordanxzz** [comment]
> I am not able to replicate your error. With a clean install of python I get the following proper functionality. What is your pandas version, perhaps that is causing an issue. The version in my example below is 0.22
> 
> ```
> Python 3.4.3 (default, Sep 14 2016, 12:36:27) 
> Type "copyright", "credits" or "license" for more information.
> 
> IPython 1.2.1 -- An enhanced Interactive Python.
> ?         -> Introduction and overview of IPython's features.
> %quickref -> Quick reference.
> help      -> Python's own help system.
> object?   -> Details about 'object', use 'object??' for extra details.
> 
> In [1]: import pandas_market_calendars as mcal
> 
> In [2]: mcal.__version__
> Out[2]: '0.21.1'
> 
> In [3]: nyse = mcal.get_calendar('NYSE')
> 
> In [4]: schedule = nyse.schedule('2018-11-01','2018-11-30')
> 
> In [5]: schedule
> Out[5]: 
>                          market_open              market_close
> 2018-11-01 2018-11-01 13:30:00+00:00 2018-11-01 20:00:00+00:00
> 2018-11-02 2018-11-02 13:30:00+00:00 2018-11-02 20:00:00+00:00
> 2018-11-05 2018-11-05 14:30:00+00:00 2018-11-05 21:00:00+00:00
> 2018-11-06 2018-11-06 14:30:00+00:00 2018-11-06 21:00:00+00:00
> 2018-11-07 2018-11-07 14:30:00+00:00 2018-11-07 21:00:00+00:00
> 2018-11-08 2018-11-08 14:30:00+00:00 2018-11-08 21:00:00+00:00
> 2018-11-09 2018-11-09 14:30:00+00:00 2018-11-09 21:00:00+00:00
> 2018-11-12 2018-11-12 14:30:00+00:00 2018-11-12 21:00:00+00:00
> 2018-11-13 2018-11-13 14:30:00+00:00 2018-11-13 21:00:00+00:00
> 2018-11-14 2018-11-14 14:30:00+00:00 2018-11-14 21:00:00+00:00
> 2018-11-15 2018-11-15 14:30:00+00:00 2018-11-15 21:00:00+00:00
> 2018-11-16 2018-11-16 14:30:00+00:00 2018-11-16 21:00:00+00:00
> 2018-11-19 2018-11-19 14:30:00+00:00 2018-11-19 21:00:00+00:00
> 2018-11-20 2018-11-20 14:30:00+00:00 2018-11-20 21:00:00+00:00
> 2018-11-21 2018-11-21 14:30:00+00:00 2018-11-21 21:00:00+00:00
> 2018-11-23 2018-11-23 14:30:00+00:00 2018-11-23 18:00:00+00:00
> 2018-11-26 2018-11-26 14:30:00+00:00 2018-11-26 21:00:00+00:00
> 2018-11-27 2018-11-27 14:30:00+00:00 2018-11-27 21:00:00+00:00
> 2018-11-28 2018-11-28 14:30:00+00:00 2018-11-28 21:00:00+00:00
> 2018-11-29 2018-11-29 14:30:00+00:00 2018-11-29 21:00:00+00:00
> 2018-11-30 2018-11-30 14:30:00+00:00 2018-11-30 21:00:00+00:00
> ```

Thanks. The thing is that it also works on my PC, but not on the linux server, which is really strange.

**Comment by rsheftel** [comment]
That is odd. One thing to check is the version of pandas on the linux server. The error looks like it is from pandas as perhaps the functionality of something in pandas changed with a version and your linux server is on an older version than your PC. This is just a guess.
