### ISSUE TITLE
For python 2.7 metaclass tag is different

### ISSUE THREAD

**Issue by bryanfok** [rsheftel/pandas_market_calendars#6]
For python 2.7 metaclass has to represent as this way? Otherwise, exception will throw

```
class MarketCalendar(object): 
    __metaclass__ = ABCMeta 
```

**Comment by rsheftel** [comment]
I am not an expert in Python 2.7 but I do believe metaclasses are defined differently than in Python3. Here is the documentation for Python 2.7 https://docs.python.org/2/library/abc.html

**Comment by bryanfok** [comment]
i am using in my local box which only 2.7 at the moment. And it fail if I dont change the metaclass definition into this. So I changed in my local branch to make it working. Therefore, if you want to make it compatible with 2.7 too, I guess you have to update in master as well.

**Comment by rsheftel** [comment]
If you submit a pull request that makes the package work for 2.7 as well as Python 3 I will review and include in the master.

**Comment by rsheftel** [comment]
Python2.7 support has been added in the latest commit v0.5  ( https://github.com/rsheftel/pandas_market_calendars/commit/ec9e1de064f37cbd2bb8a429a9be509126028278 ) This has not been uploaded to PyPi yet so use the GitHub version.
