### ISSUE TITLE
London calendar does not account for Queen's Diamond Jubilee Holidays

### ISSUE THREAD

**Issue by harry-wright** [rsheftel/pandas_market_calendars#60]
Can you please account for the following dates in the london schedule as this has caused a headache wondering why data wasn't being returned for these dates:

```
# Bank Holiday + Queen's Diamond Jubilee
schedule.drop([pd.Timestamp('2012-06-04T00:00:00.000000000'), pd.Timestamp('2012-06-05T00:00:00.000000000')], inplace=True)
```

**Comment by harry-wright** [comment]
Just to clarify these WERE NOT trading dates

**Comment by rsheftel** [comment]
These holidays have been added in ecd8ec4864f98f2c516cd6977e2c294a38d68879
