### ISSUE TITLE
Japan Calendar needs work

### ISSUE THREAD

**Issue by lks100** [rsheftel/pandas_market_calendars#71]
FYI, I found some problems in the JPX calendar.  I have fixed all these problems in my private copy, and I have verified my changes against a list of dates for the Nikkei 225 index since 5/16/1949.

I will submit a patch as soon as I get a chance to write a few tests. 

Here are the problems I found:

For dates before 1973 or so, holidays landing on a Sunday did not generally close the exchange on a Monday.

There were certain holidays that did not have a start date (some holidays only began after 1948).

The exchange was closed on December 29 and 30 until 1989.

The Emperor's birthday is switching in 2020, and this is not reflected in the prospective calendar holidays.

For 2020 also, due to the Olympics, a number of holidays are switching around, and Health and Sports Day is being renamed Sports Day starting in 2020.

No vernal or autumnal projected dates were included past 2031 (I needed the calendar through 2099).

**Comment by rsheftel** [comment]
That's great thanks you. I look forward to the PR

**Comment by rsheftel** [comment]
Thanks for the PR. everything merged
