### ISSUE TITLE
Schedule and date_range mismatch

### ISSUE THREAD

**Issue by vakker** [rsheftel/pandas_market_calendars#78]
I was trying to use the `date_range` function and it seems like it returns the time with an hour offset, e.g.:
```
>>> schedule = lse.schedule(start_date='2016-12-30', end_date='2017-01-10')
>>> schedule
                         market_open              market_close
2016-12-30 2016-12-30 08:00:00+00:00 2016-12-30 12:30:00+00:00
2017-01-03 2017-01-03 08:00:00+00:00 2017-01-03 16:30:00+00:00
2017-01-04 2017-01-04 08:00:00+00:00 2017-01-04 16:30:00+00:00
2017-01-05 2017-01-05 08:00:00+00:00 2017-01-05 16:30:00+00:00
2017-01-06 2017-01-06 08:00:00+00:00 2017-01-06 16:30:00+00:00
2017-01-09 2017-01-09 08:00:00+00:00 2017-01-09 16:30:00+00:00
2017-01-10 2017-01-10 08:00:00+00:00 2017-01-10 16:30:00+00:00

>>> schedule.iloc[0]
market_open    2016-12-30 08:00:00+00:00
market_close   2016-12-30 12:30:00+00:00
Name: 2016-12-30 00:00:00, dtype: datetime64[ns, UTC]

>>> d=mcal.date_range(schedule, frequency='1H')
>>> d[:10]
DatetimeIndex(['2016-12-30 09:00:00+00:00', '2016-12-30 10:00:00+00:00',
               '2016-12-30 11:00:00+00:00', '2016-12-30 12:00:00+00:00',
               '2016-12-30 12:30:00+00:00', '2017-01-03 09:00:00+00:00',
               '2017-01-03 10:00:00+00:00', '2017-01-03 11:00:00+00:00',
               '2017-01-03 12:00:00+00:00', '2017-01-03 13:00:00+00:00'],
              dtype='datetime64[ns, UTC]', freq=None)
```

I would assume that the `date_range` started at 08:00:00, not at 9. Is this intended?

**Comment by rsheftel** [comment]
The date_range() function by default returns times in UTC for the **end** of each time frame. So in your example the first value in d is "2016-12-30 09:00:00+00:00" which represents the end of that first time slice. This is controlled by the closed parameter. From the docs:

> closed: same meaning as pandas date_range. 'right' will exclude the first value and should be used when the results should only include the close for each bar.

Here are the docs for the pandas date_time function: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.date_range.html

To generate a DateTimeIndex that includes that first open time as well set that parameter to None:

`d2=mcal.date_range(schedule, frequency='1H', closed=None)`

`DatetimeIndex(['2016-12-30 08:00:00+00:00', '2016-12-30 09:00:00+00:00',
'2016-12-30 10:00:00+00:00', '2016-12-30 11:00:00+00:00',
               '2016-12-30 12:00:00+00:00', '2016-12-30 12:30:00+00:00',
               '2017-01-03 08:00:00+00:00', '2017-01-03 09:00:00+00:00',
               '2017-01-03 10:00:00+00:00', '2017-01-03 11:00:00+00:00'],
              dtype='datetime64[ns, UTC]', freq=None)`
