### ISSUE TITLE
Warning deprecation

### ISSUE THREAD

**Issue by Franlodo** [rsheftel/pandas_market_calendars#8]
I get this warning:
Warning (from warnings module):
  File "D:\Phyton\lib\site-packages\pandas_market_calendars\exchange_calendar_ice.py", line 10
    from pandas.tslib import Timestamp
FutureWarning: The pandas.tslib module is deprecated and will be removed in a future version.

Something else ... Could you change the examples in documents where is "import pandas_exchange_calendars" written for "import pandas_market_calendars"?

I told in http://pandas-market-calendars.readthedocs.io/en/latest/

Thank's for all and great module

**Comment by rsheftel** [comment]
Thanks for the comments. All changes have been implemented and committed.
