### ISSUE TITLE
Are these all London hours?

### ISSUE THREAD

**Issue by luoyudong593** [rsheftel/pandas_market_calendars#82]
Are these all London hours?
![1578038931(1)](https://user-images.githubusercontent.com/54063226/71791152-d8335500-306e-11ea-8c6e-7e51a802259d.jpg)

**Comment by rsheftel** [comment]
They are in UTC time. You can tell from the "+00:00" on the end of the times. that is the universal code for the offset from UTC.

Pandas has many useful functions to localize these into any other time zone

**Comment by luoyudong593** [comment]
> They are in UTC time. You can tell from the "+00:00" on the end of the times. that is the universal code for the offset from UTC.
> 
> Pandas has many useful functions to localize these into any other time zone

 Thank you very much~
