### ISSUE TITLE
Add is_open_now convenience method

### ISSUE THREAD

**Issue by kennell** [rsheftel/pandas_market_calendars#87]
It would be very convenient to have a `is_open_now` method (naming to be discussed) that returns True/False based on the systems current datetime, without having to explicitly pass a timestamp.

**Comment by rsheftel** [comment]
@kennell if you would like to submit a PR with that I would be happy to review.

**Comment by leonarduschen** [comment]
Hi @kennell are you working on this? I'd like to go for this if you don't mind.

@rsheftel I'm thinking of adding `is_open_now` as a staticmethod to `MarketCalendar`, similar to the `open_at_time`.

If everything sounds good, I'll go ahead and submit a PR, this will be my first open-source contribution though.

**Comment by rsheftel** [comment]
@kneell That works for me

**Comment by kennell** [comment]
@leonarduschen No, haven't done any work on this, feel free to go for it

**Comment by rsheftel** [comment]
#115 #87 covers this
