### ISSUE TITLE
CME schedule displaying invalid dates

### ISSUE THREAD

**Issue by lionelyoung** [rsheftel/pandas_market_calendars#88]
I'm receiving bad dates when I use the CME calendar.  

I could get the holiday's via `cme.early_closes(schedule)` but these are regular holidays for CME, and not early closes:
>             USNewYearsDay,
>             USMartinLutherKingJrAfter1998,
>             USPresidentsDay,
>             GoodFriday,
>             USMemorialDay,
>             USIndependenceDay,
>             USLaborDay,
>             USThanksgivingDay,
>             Christmas,

Here is a code snippet that demonstrates:

```
import pandas_market_calendars as mcal
import pandas as pd
cme = mcal.get_calendar("CME")
schedule = cme.schedule(start_date="2020-01-01", end_date="2020-12-31")
print(schedule)
sessions = schedule["market_close"]

# See 2020 Calendar here:
# http://investor.cmegroup.com/static-files/bae826b9-bac3-4559-be69-0f5e04fc9c2b
INVALID_HOLIDAYS_FOR_TRADING = [
    "2020-01-20",
    "2020-02-17",
    "2020-04-10",
    "2020-05-25",
    "2020-07-03",
    "2020-09-07",
    "2020-11-26",
    "2020-12-25",
]

for day in INVALID_HOLIDAYS_FOR_TRADING:
    if pd.to_datetime(day) in sessions:
        print(f"ERROR: {day} found in schedule")
    else:
        print(f"OK: {day} not in schedule")


```

This gave me: 

> ERROR: 2020-01-20 found in schedule
> ERROR: 2020-02-17 found in schedule
> OK: 2020-04-10 not in schedule
> ERROR: 2020-05-25 found in schedule
> ERROR: 2020-07-03 found in schedule
> ERROR: 2020-09-07 found in schedule
> ERROR: 2020-11-26 found in schedule
> OK: 2020-12-25 not in schedule

Versions:

- Python: 3.6.1
- pandas 1.0.2
- pandas_market_calendars 1.2

**Comment by rsheftel** [comment]
The CME calendars need a major overhaul because right now it is just a single generic calendar for all the different markets. This needs to be split into product specific markets like:

- CME_equity
- CME_fixed_income
- CME_energy
....etc

If you have the time and would to start that on a PR would be great.

**Comment by lionelyoung** [comment]
I pulled up every compact calendar on https://www.cmegroup.com/tools-information/holiday-calendar.html to review, and I leaned toward avoiding special rules rather than including.

Let me know if you have a "special rules" structure in mind already

**Comment by rsheftel** [comment]
This is great, I will review the PR and look to add this shortly.
