### ISSUE TITLE
Feature Request: Calendar for Singapore?

### ISSUE THREAD

**Issue by haimivan** [rsheftel/pandas_market_calendars#92]
Hi,

would it be possible to add also the calendar for Singapore?

Thanks in advance!

**Comment by rsheftel** [comment]
All calendars are community supplied. There are explanations in the docs [here ](https://pandas-market-calendars.readthedocs.io/en/latest/new_market.html)on how to create a new calendar. If you make one and submit a PR I will review and merge.
