### ISSUE TITLE
Handle Middle of Session Non-Trading

### ISSUE THREAD

**Issue by lionelyoung** [rsheftel/pandas_market_calendars#94]
What are your thoughts on removing hours in the middle of a session?

Equity futures have a pause between 13:20 and 14:30 CT, and a feature like the example below could implement it.

The example removes lunch times:

https://github.com/alphamodel/pandas_market_calendars/commit/eca370e509f792d7f27e01128ca9d589b02c8e64

P.S. We could also use this to handle historical lock limits, though that may be out of scope of this package.

**Comment by rsheftel** [comment]
I think this could be a great addition. Two questions:

1) why is it called a "hint_exchange"?
2) Do you have an example of the usage?

**Comment by rsheftel** [comment]
When this is added, apply to SSE

**Comment by rsheftel** [comment]
@lionelyoung thanks for this suggestion. It has been implemented in edf44bbcc6db2994644eeb96285fe3cf288b64a4 and will be pushed to PyPi when I release v1.4
