### ISSUE TITLE
NYSE Calendar Date Missing

### ISSUE THREAD

**Issue by allan8392** [rsheftel/pandas_market_calendars#97]
Hi,
     I discovered that 2018-12-05 is missing from NYSE calendar even though that day is not a 
     holiday. Please see below:
> import datetime
import pandas_market_calendars as mcal
exch = 'NYSE'
first = datetime.date(2018, 12, 1)
last = datetime.date(2018, 12, 10)
a = mcal.get_calendar(exch).valid_days(first, last)
print(a)

> DatetimeIndex(['2018-12-03 00:00:00+00:00', '2018-12-04 00:00:00+00:00',
               '2018-12-06 00:00:00+00:00', '2018-12-07 00:00:00+00:00',
               '2018-12-10 00:00:00+00:00'],
              dtype='datetime64[ns, UTC]', freq='C')

**Comment by rsheftel** [comment]
The US equity markets and exchanges were closed on 12/5/18 in for President Bush's funeral:

https://www.reuters.com/article/us-people-bush-economy-factbox/us-event-market-closures-for-funeral-of-former-president-bush-idUSKBN1O22LM

That holiday is correct.
